// Code generated by ent, DO NOT EDIT.

package routepolicy

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the routepolicy type in the database.
	Label = "route_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMatchMethod holds the string denoting the match_method field in the database.
	FieldMatchMethod = "match_method"
	// FieldMatchPath holds the string denoting the match_path field in the database.
	FieldMatchPath = "match_path"
	// FieldMatchModel holds the string denoting the match_model field in the database.
	FieldMatchModel = "match_model"
	// FieldMatchCapability holds the string denoting the match_capability field in the database.
	FieldMatchCapability = "match_capability"
	// FieldMatchGroupPlatform holds the string denoting the match_group_platform field in the database.
	FieldMatchGroupPlatform = "match_group_platform"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldAdapterProviderID holds the string denoting the adapter_provider_id field in the database.
	FieldAdapterProviderID = "adapter_provider_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldConditions holds the string denoting the conditions field in the database.
	FieldConditions = "conditions"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeAdapterProvider holds the string denoting the adapter_provider edge name in mutations.
	EdgeAdapterProvider = "adapter_provider"
	// EdgeAdapterUsageRecords holds the string denoting the adapter_usage_records edge name in mutations.
	EdgeAdapterUsageRecords = "adapter_usage_records"
	// Table holds the table name of the routepolicy in the database.
	Table = "route_policies"
	// AdapterProviderTable is the table that holds the adapter_provider relation/edge.
	AdapterProviderTable = "route_policies"
	// AdapterProviderInverseTable is the table name for the AdapterProvider entity.
	// It exists in this package in order to avoid circular dependency with the "adapterprovider" package.
	AdapterProviderInverseTable = "adapter_providers"
	// AdapterProviderColumn is the table column denoting the adapter_provider relation/edge.
	AdapterProviderColumn = "adapter_provider_id"
	// AdapterUsageRecordsTable is the table that holds the adapter_usage_records relation/edge.
	AdapterUsageRecordsTable = "adapter_usage_records"
	// AdapterUsageRecordsInverseTable is the table name for the AdapterUsageRecord entity.
	// It exists in this package in order to avoid circular dependency with the "adapterusagerecord" package.
	AdapterUsageRecordsInverseTable = "adapter_usage_records"
	// AdapterUsageRecordsColumn is the table column denoting the adapter_usage_records relation/edge.
	AdapterUsageRecordsColumn = "route_policy_id"
)

// Columns holds all SQL columns for routepolicy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldStatus,
	FieldMatchMethod,
	FieldMatchPath,
	FieldMatchModel,
	FieldMatchCapability,
	FieldMatchGroupPlatform,
	FieldTarget,
	FieldPlatform,
	FieldAdapterProviderID,
	FieldPriority,
	FieldConditions,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// MatchMethodValidator is a validator for the "match_method" field. It is called by the builders before save.
	MatchMethodValidator func(string) error
	// MatchPathValidator is a validator for the "match_path" field. It is called by the builders before save.
	MatchPathValidator func(string) error
	// MatchModelValidator is a validator for the "match_model" field. It is called by the builders before save.
	MatchModelValidator func(string) error
	// MatchCapabilityValidator is a validator for the "match_capability" field. It is called by the builders before save.
	MatchCapabilityValidator func(string) error
	// MatchGroupPlatformValidator is a validator for the "match_group_platform" field. It is called by the builders before save.
	MatchGroupPlatformValidator func(string) error
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
)

// OrderOption defines the ordering options for the RoutePolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMatchMethod orders the results by the match_method field.
func ByMatchMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchMethod, opts...).ToFunc()
}

// ByMatchPath orders the results by the match_path field.
func ByMatchPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchPath, opts...).ToFunc()
}

// ByMatchModel orders the results by the match_model field.
func ByMatchModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchModel, opts...).ToFunc()
}

// ByMatchCapability orders the results by the match_capability field.
func ByMatchCapability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchCapability, opts...).ToFunc()
}

// ByMatchGroupPlatform orders the results by the match_group_platform field.
func ByMatchGroupPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchGroupPlatform, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByAdapterProviderID orders the results by the adapter_provider_id field.
func ByAdapterProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapterProviderID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAdapterProviderField orders the results by adapter_provider field.
func ByAdapterProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdapterProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByAdapterUsageRecordsCount orders the results by adapter_usage_records count.
func ByAdapterUsageRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdapterUsageRecordsStep(), opts...)
	}
}

// ByAdapterUsageRecords orders the results by adapter_usage_records terms.
func ByAdapterUsageRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdapterUsageRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAdapterProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdapterProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AdapterProviderTable, AdapterProviderColumn),
	)
}
func newAdapterUsageRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdapterUsageRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdapterUsageRecordsTable, AdapterUsageRecordsColumn),
	)
}
