// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterrequest"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdapterRequestCreate is the builder for creating a AdapterRequest entity.
type AdapterRequestCreate struct {
	config
	mutation *AdapterRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *AdapterRequestCreate) SetRequestID(v string) *AdapterRequestCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AdapterRequestCreate) SetUserID(v int64) *AdapterRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *AdapterRequestCreate) SetAPIKeyID(v int64) *AdapterRequestCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AdapterRequestCreate) SetGroupID(v int64) *AdapterRequestCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableGroupID(v *int64) *AdapterRequestCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (_c *AdapterRequestCreate) SetAdapterProviderID(v int64) *AdapterRequestCreate {
	_c.mutation.SetAdapterProviderID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AdapterRequestCreate) SetProvider(v string) *AdapterRequestCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetCapability sets the "capability" field.
func (_c *AdapterRequestCreate) SetCapability(v string) *AdapterRequestCreate {
	_c.mutation.SetCapability(v)
	return _c
}

// SetRouteTarget sets the "route_target" field.
func (_c *AdapterRequestCreate) SetRouteTarget(v string) *AdapterRequestCreate {
	_c.mutation.SetRouteTarget(v)
	return _c
}

// SetNillableRouteTarget sets the "route_target" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableRouteTarget(v *string) *AdapterRequestCreate {
	if v != nil {
		_c.SetRouteTarget(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AdapterRequestCreate) SetMethod(v string) *AdapterRequestCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *AdapterRequestCreate) SetPath(v string) *AdapterRequestCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AdapterRequestCreate) SetModel(v string) *AdapterRequestCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableModel(v *string) *AdapterRequestCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AdapterRequestCreate) SetStatusCode(v int) *AdapterRequestCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableStatusCode(v *int) *AdapterRequestCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AdapterRequestCreate) SetDurationMs(v int) *AdapterRequestCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableDurationMs(v *int) *AdapterRequestCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AdapterRequestCreate) SetErrorMessage(v string) *AdapterRequestCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableErrorMessage(v *string) *AdapterRequestCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AdapterRequestCreate) SetMetadata(v map[string]interface{}) *AdapterRequestCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdapterRequestCreate) SetCreatedAt(v time.Time) *AdapterRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdapterRequestCreate) SetNillableCreatedAt(v *time.Time) *AdapterRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AdapterRequestCreate) SetUser(v *User) *AdapterRequestCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *AdapterRequestCreate) SetAPIKey(v *APIKey) *AdapterRequestCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *AdapterRequestCreate) SetGroup(v *Group) *AdapterRequestCreate {
	return _c.SetGroupID(v.ID)
}

// SetAdapterProvider sets the "adapter_provider" edge to the AdapterProvider entity.
func (_c *AdapterRequestCreate) SetAdapterProvider(v *AdapterProvider) *AdapterRequestCreate {
	return _c.SetAdapterProviderID(v.ID)
}

// Mutation returns the AdapterRequestMutation object of the builder.
func (_c *AdapterRequestCreate) Mutation() *AdapterRequestMutation {
	return _c.mutation
}

// Save creates the AdapterRequest in the database.
func (_c *AdapterRequestCreate) Save(ctx context.Context) (*AdapterRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdapterRequestCreate) SaveX(ctx context.Context) *AdapterRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdapterRequestCreate) defaults() {
	if _, ok := _c.mutation.RouteTarget(); !ok {
		v := adapterrequest.DefaultRouteTarget
		_c.mutation.SetRouteTarget(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adapterrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdapterRequestCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "AdapterRequest.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := adapterrequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AdapterRequest.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "AdapterRequest.api_key_id"`)}
	}
	if _, ok := _c.mutation.AdapterProviderID(); !ok {
		return &ValidationError{Name: "adapter_provider_id", err: errors.New(`ent: missing required field "AdapterRequest.adapter_provider_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AdapterRequest.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := adapterrequest.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capability(); !ok {
		return &ValidationError{Name: "capability", err: errors.New(`ent: missing required field "AdapterRequest.capability"`)}
	}
	if v, ok := _c.mutation.Capability(); ok {
		if err := adapterrequest.CapabilityValidator(v); err != nil {
			return &ValidationError{Name: "capability", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.capability": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RouteTarget(); !ok {
		return &ValidationError{Name: "route_target", err: errors.New(`ent: missing required field "AdapterRequest.route_target"`)}
	}
	if v, ok := _c.mutation.RouteTarget(); ok {
		if err := adapterrequest.RouteTargetValidator(v); err != nil {
			return &ValidationError{Name: "route_target", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.route_target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "AdapterRequest.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := adapterrequest.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AdapterRequest.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := adapterrequest.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := adapterrequest.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdapterRequest.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AdapterRequest.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "AdapterRequest.api_key"`)}
	}
	if len(_c.mutation.AdapterProviderIDs()) == 0 {
		return &ValidationError{Name: "adapter_provider", err: errors.New(`ent: missing required edge "AdapterRequest.adapter_provider"`)}
	}
	return nil
}

func (_c *AdapterRequestCreate) sqlSave(ctx context.Context) (*AdapterRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdapterRequestCreate) createSpec() (*AdapterRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &AdapterRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adapterrequest.Table, sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(adapterrequest.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(adapterrequest.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Capability(); ok {
		_spec.SetField(adapterrequest.FieldCapability, field.TypeString, value)
		_node.Capability = value
	}
	if value, ok := _c.mutation.RouteTarget(); ok {
		_spec.SetField(adapterrequest.FieldRouteTarget, field.TypeString, value)
		_node.RouteTarget = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(adapterrequest.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(adapterrequest.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(adapterrequest.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(adapterrequest.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(adapterrequest.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(adapterrequest.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(adapterrequest.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adapterrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.UserTable,
			Columns: []string{adapterrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.APIKeyTable,
			Columns: []string{adapterrequest.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.GroupTable,
			Columns: []string{adapterrequest.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdapterProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.AdapterProviderTable,
			Columns: []string{adapterrequest.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdapterProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterRequest.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterRequestUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterRequestCreate) OnConflict(opts ...sql.ConflictOption) *AdapterRequestUpsertOne {
	_c.conflict = opts
	return &AdapterRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterRequestCreate) OnConflictColumns(columns ...string) *AdapterRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterRequestUpsertOne{
		create: _c,
	}
}

type (
	// AdapterRequestUpsertOne is the builder for "upsert"-ing
	//  one AdapterRequest node.
	AdapterRequestUpsertOne struct {
		create *AdapterRequestCreate
	}

	// AdapterRequestUpsert is the "OnConflict" setter.
	AdapterRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *AdapterRequestUpsert) SetRequestID(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateRequestID() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdapterRequestUpsert) SetUserID(v int64) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateUserID() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterRequestUpsert) SetAPIKeyID(v int64) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateAPIKeyID() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AdapterRequestUpsert) SetGroupID(v int64) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateGroupID() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterRequestUpsert) ClearGroupID() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldGroupID)
	return u
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterRequestUpsert) SetAdapterProviderID(v int64) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldAdapterProviderID, v)
	return u
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateAdapterProviderID() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldAdapterProviderID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AdapterRequestUpsert) SetProvider(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateProvider() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldProvider)
	return u
}

// SetCapability sets the "capability" field.
func (u *AdapterRequestUpsert) SetCapability(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldCapability, v)
	return u
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateCapability() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldCapability)
	return u
}

// SetRouteTarget sets the "route_target" field.
func (u *AdapterRequestUpsert) SetRouteTarget(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldRouteTarget, v)
	return u
}

// UpdateRouteTarget sets the "route_target" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateRouteTarget() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldRouteTarget)
	return u
}

// SetMethod sets the "method" field.
func (u *AdapterRequestUpsert) SetMethod(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateMethod() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldMethod)
	return u
}

// SetPath sets the "path" field.
func (u *AdapterRequestUpsert) SetPath(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdatePath() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldPath)
	return u
}

// SetModel sets the "model" field.
func (u *AdapterRequestUpsert) SetModel(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateModel() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AdapterRequestUpsert) ClearModel() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldModel)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterRequestUpsert) SetStatusCode(v int) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateStatusCode() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterRequestUpsert) AddStatusCode(v int) *AdapterRequestUpsert {
	u.Add(adapterrequest.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterRequestUpsert) ClearStatusCode() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldStatusCode)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterRequestUpsert) SetDurationMs(v int) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateDurationMs() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterRequestUpsert) AddDurationMs(v int) *AdapterRequestUpsert {
	u.Add(adapterrequest.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterRequestUpsert) ClearDurationMs() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldDurationMs)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterRequestUpsert) SetErrorMessage(v string) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateErrorMessage() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterRequestUpsert) ClearErrorMessage() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldErrorMessage)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *AdapterRequestUpsert) SetMetadata(v map[string]interface{}) *AdapterRequestUpsert {
	u.Set(adapterrequest.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterRequestUpsert) UpdateMetadata() *AdapterRequestUpsert {
	u.SetExcluded(adapterrequest.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterRequestUpsert) ClearMetadata() *AdapterRequestUpsert {
	u.SetNull(adapterrequest.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterRequestUpsertOne) UpdateNewValues() *AdapterRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adapterrequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdapterRequestUpsertOne) Ignore() *AdapterRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterRequestUpsertOne) DoNothing() *AdapterRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterRequestCreate.OnConflict
// documentation for more info.
func (u *AdapterRequestUpsertOne) Update(set func(*AdapterRequestUpsert)) *AdapterRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AdapterRequestUpsertOne) SetRequestID(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateRequestID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdapterRequestUpsertOne) SetUserID(v int64) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateUserID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterRequestUpsertOne) SetAPIKeyID(v int64) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateAPIKeyID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AdapterRequestUpsertOne) SetGroupID(v int64) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateGroupID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterRequestUpsertOne) ClearGroupID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearGroupID()
	})
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterRequestUpsertOne) SetAdapterProviderID(v int64) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetAdapterProviderID(v)
	})
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateAdapterProviderID() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateAdapterProviderID()
	})
}

// SetProvider sets the "provider" field.
func (u *AdapterRequestUpsertOne) SetProvider(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateProvider() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateProvider()
	})
}

// SetCapability sets the "capability" field.
func (u *AdapterRequestUpsertOne) SetCapability(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetCapability(v)
	})
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateCapability() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateCapability()
	})
}

// SetRouteTarget sets the "route_target" field.
func (u *AdapterRequestUpsertOne) SetRouteTarget(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetRouteTarget(v)
	})
}

// UpdateRouteTarget sets the "route_target" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateRouteTarget() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateRouteTarget()
	})
}

// SetMethod sets the "method" field.
func (u *AdapterRequestUpsertOne) SetMethod(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateMethod() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateMethod()
	})
}

// SetPath sets the "path" field.
func (u *AdapterRequestUpsertOne) SetPath(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdatePath() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdatePath()
	})
}

// SetModel sets the "model" field.
func (u *AdapterRequestUpsertOne) SetModel(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateModel() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AdapterRequestUpsertOne) ClearModel() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearModel()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterRequestUpsertOne) SetStatusCode(v int) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterRequestUpsertOne) AddStatusCode(v int) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateStatusCode() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterRequestUpsertOne) ClearStatusCode() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterRequestUpsertOne) SetDurationMs(v int) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterRequestUpsertOne) AddDurationMs(v int) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateDurationMs() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterRequestUpsertOne) ClearDurationMs() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearDurationMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterRequestUpsertOne) SetErrorMessage(v string) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateErrorMessage() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterRequestUpsertOne) ClearErrorMessage() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearErrorMessage()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AdapterRequestUpsertOne) SetMetadata(v map[string]interface{}) *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterRequestUpsertOne) UpdateMetadata() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterRequestUpsertOne) ClearMetadata() *AdapterRequestUpsertOne {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AdapterRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdapterRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdapterRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdapterRequestCreateBulk is the builder for creating many AdapterRequest entities in bulk.
type AdapterRequestCreateBulk struct {
	config
	err      error
	builders []*AdapterRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the AdapterRequest entities in the database.
func (_c *AdapterRequestCreateBulk) Save(ctx context.Context) ([]*AdapterRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdapterRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdapterRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdapterRequestCreateBulk) SaveX(ctx context.Context) []*AdapterRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterRequestUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdapterRequestUpsertBulk {
	_c.conflict = opts
	return &AdapterRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterRequestCreateBulk) OnConflictColumns(columns ...string) *AdapterRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterRequestUpsertBulk{
		create: _c,
	}
}

// AdapterRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of AdapterRequest nodes.
type AdapterRequestUpsertBulk struct {
	create *AdapterRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterRequestUpsertBulk) UpdateNewValues() *AdapterRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adapterrequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdapterRequestUpsertBulk) Ignore() *AdapterRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterRequestUpsertBulk) DoNothing() *AdapterRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterRequestCreateBulk.OnConflict
// documentation for more info.
func (u *AdapterRequestUpsertBulk) Update(set func(*AdapterRequestUpsert)) *AdapterRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AdapterRequestUpsertBulk) SetRequestID(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateRequestID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdapterRequestUpsertBulk) SetUserID(v int64) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateUserID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterRequestUpsertBulk) SetAPIKeyID(v int64) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateAPIKeyID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AdapterRequestUpsertBulk) SetGroupID(v int64) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateGroupID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterRequestUpsertBulk) ClearGroupID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearGroupID()
	})
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterRequestUpsertBulk) SetAdapterProviderID(v int64) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetAdapterProviderID(v)
	})
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateAdapterProviderID() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateAdapterProviderID()
	})
}

// SetProvider sets the "provider" field.
func (u *AdapterRequestUpsertBulk) SetProvider(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateProvider() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateProvider()
	})
}

// SetCapability sets the "capability" field.
func (u *AdapterRequestUpsertBulk) SetCapability(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetCapability(v)
	})
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateCapability() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateCapability()
	})
}

// SetRouteTarget sets the "route_target" field.
func (u *AdapterRequestUpsertBulk) SetRouteTarget(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetRouteTarget(v)
	})
}

// UpdateRouteTarget sets the "route_target" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateRouteTarget() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateRouteTarget()
	})
}

// SetMethod sets the "method" field.
func (u *AdapterRequestUpsertBulk) SetMethod(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateMethod() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateMethod()
	})
}

// SetPath sets the "path" field.
func (u *AdapterRequestUpsertBulk) SetPath(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdatePath() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdatePath()
	})
}

// SetModel sets the "model" field.
func (u *AdapterRequestUpsertBulk) SetModel(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateModel() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AdapterRequestUpsertBulk) ClearModel() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearModel()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterRequestUpsertBulk) SetStatusCode(v int) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterRequestUpsertBulk) AddStatusCode(v int) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateStatusCode() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterRequestUpsertBulk) ClearStatusCode() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterRequestUpsertBulk) SetDurationMs(v int) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterRequestUpsertBulk) AddDurationMs(v int) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateDurationMs() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterRequestUpsertBulk) ClearDurationMs() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearDurationMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterRequestUpsertBulk) SetErrorMessage(v string) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateErrorMessage() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterRequestUpsertBulk) ClearErrorMessage() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearErrorMessage()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AdapterRequestUpsertBulk) SetMetadata(v map[string]interface{}) *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterRequestUpsertBulk) UpdateMetadata() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterRequestUpsertBulk) ClearMetadata() *AdapterRequestUpsertBulk {
	return u.Update(func(s *AdapterRequestUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AdapterRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdapterRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
