// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterrequest"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdapterRequestQuery is the builder for querying AdapterRequest entities.
type AdapterRequestQuery struct {
	config
	ctx                 *QueryContext
	order               []adapterrequest.OrderOption
	inters              []Interceptor
	predicates          []predicate.AdapterRequest
	withUser            *UserQuery
	withAPIKey          *APIKeyQuery
	withGroup           *GroupQuery
	withAdapterProvider *AdapterProviderQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdapterRequestQuery builder.
func (_q *AdapterRequestQuery) Where(ps ...predicate.AdapterRequest) *AdapterRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AdapterRequestQuery) Limit(limit int) *AdapterRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AdapterRequestQuery) Offset(offset int) *AdapterRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AdapterRequestQuery) Unique(unique bool) *AdapterRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AdapterRequestQuery) Order(o ...adapterrequest.OrderOption) *AdapterRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *AdapterRequestQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adapterrequest.Table, adapterrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adapterrequest.UserTable, adapterrequest.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAPIKey chains the current query on the "api_key" edge.
func (_q *AdapterRequestQuery) QueryAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adapterrequest.Table, adapterrequest.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adapterrequest.APIKeyTable, adapterrequest.APIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *AdapterRequestQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adapterrequest.Table, adapterrequest.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adapterrequest.GroupTable, adapterrequest.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdapterProvider chains the current query on the "adapter_provider" edge.
func (_q *AdapterRequestQuery) QueryAdapterProvider() *AdapterProviderQuery {
	query := (&AdapterProviderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adapterrequest.Table, adapterrequest.FieldID, selector),
			sqlgraph.To(adapterprovider.Table, adapterprovider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adapterrequest.AdapterProviderTable, adapterrequest.AdapterProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdapterRequest entity from the query.
// Returns a *NotFoundError when no AdapterRequest was found.
func (_q *AdapterRequestQuery) First(ctx context.Context) (*AdapterRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adapterrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AdapterRequestQuery) FirstX(ctx context.Context) *AdapterRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdapterRequest ID from the query.
// Returns a *NotFoundError when no AdapterRequest ID was found.
func (_q *AdapterRequestQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adapterrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AdapterRequestQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdapterRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdapterRequest entity is found.
// Returns a *NotFoundError when no AdapterRequest entities are found.
func (_q *AdapterRequestQuery) Only(ctx context.Context) (*AdapterRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adapterrequest.Label}
	default:
		return nil, &NotSingularError{adapterrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AdapterRequestQuery) OnlyX(ctx context.Context) *AdapterRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdapterRequest ID in the query.
// Returns a *NotSingularError when more than one AdapterRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AdapterRequestQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adapterrequest.Label}
	default:
		err = &NotSingularError{adapterrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AdapterRequestQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdapterRequests.
func (_q *AdapterRequestQuery) All(ctx context.Context) ([]*AdapterRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdapterRequest, *AdapterRequestQuery]()
	return withInterceptors[[]*AdapterRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AdapterRequestQuery) AllX(ctx context.Context) []*AdapterRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdapterRequest IDs.
func (_q *AdapterRequestQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(adapterrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AdapterRequestQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AdapterRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AdapterRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AdapterRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AdapterRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AdapterRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdapterRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AdapterRequestQuery) Clone() *AdapterRequestQuery {
	if _q == nil {
		return nil
	}
	return &AdapterRequestQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]adapterrequest.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.AdapterRequest{}, _q.predicates...),
		withUser:            _q.withUser.Clone(),
		withAPIKey:          _q.withAPIKey.Clone(),
		withGroup:           _q.withGroup.Clone(),
		withAdapterProvider: _q.withAdapterProvider.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterRequestQuery) WithUser(opts ...func(*UserQuery)) *AdapterRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterRequestQuery) WithAPIKey(opts ...func(*APIKeyQuery)) *AdapterRequestQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKey = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterRequestQuery) WithGroup(opts ...func(*GroupQuery)) *AdapterRequestQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithAdapterProvider tells the query-builder to eager-load the nodes that are connected to
// the "adapter_provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdapterRequestQuery) WithAdapterProvider(opts ...func(*AdapterProviderQuery)) *AdapterRequestQuery {
	query := (&AdapterProviderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdapterProvider = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdapterRequest.Query().
//		GroupBy(adapterrequest.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AdapterRequestQuery) GroupBy(field string, fields ...string) *AdapterRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdapterRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = adapterrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//	}
//
//	client.AdapterRequest.Query().
//		Select(adapterrequest.FieldRequestID).
//		Scan(ctx, &v)
func (_q *AdapterRequestQuery) Select(fields ...string) *AdapterRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AdapterRequestSelect{AdapterRequestQuery: _q}
	sbuild.label = adapterrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdapterRequestSelect configured with the given aggregations.
func (_q *AdapterRequestQuery) Aggregate(fns ...AggregateFunc) *AdapterRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AdapterRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !adapterrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AdapterRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdapterRequest, error) {
	var (
		nodes       = []*AdapterRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withAPIKey != nil,
			_q.withGroup != nil,
			_q.withAdapterProvider != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdapterRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdapterRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *AdapterRequest, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAPIKey; query != nil {
		if err := _q.loadAPIKey(ctx, query, nodes, nil,
			func(n *AdapterRequest, e *APIKey) { n.Edges.APIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *AdapterRequest, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdapterProvider; query != nil {
		if err := _q.loadAdapterProvider(ctx, query, nodes, nil,
			func(n *AdapterRequest, e *AdapterProvider) { n.Edges.AdapterProvider = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AdapterRequestQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*AdapterRequest, init func(*AdapterRequest), assign func(*AdapterRequest, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdapterRequest)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdapterRequestQuery) loadAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*AdapterRequest, init func(*AdapterRequest), assign func(*AdapterRequest, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdapterRequest)
	for i := range nodes {
		fk := nodes[i].APIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdapterRequestQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*AdapterRequest, init func(*AdapterRequest), assign func(*AdapterRequest, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdapterRequest)
	for i := range nodes {
		if nodes[i].GroupID == nil {
			continue
		}
		fk := *nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdapterRequestQuery) loadAdapterProvider(ctx context.Context, query *AdapterProviderQuery, nodes []*AdapterRequest, init func(*AdapterRequest), assign func(*AdapterRequest, *AdapterProvider)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdapterRequest)
	for i := range nodes {
		fk := nodes[i].AdapterProviderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adapterprovider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "adapter_provider_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AdapterRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AdapterRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adapterrequest.Table, adapterrequest.Columns, sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adapterrequest.FieldID)
		for i := range fields {
			if fields[i] != adapterrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(adapterrequest.FieldUserID)
		}
		if _q.withAPIKey != nil {
			_spec.Node.AddColumnOnce(adapterrequest.FieldAPIKeyID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(adapterrequest.FieldGroupID)
		}
		if _q.withAdapterProvider != nil {
			_spec.Node.AddColumnOnce(adapterrequest.FieldAdapterProviderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AdapterRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(adapterrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = adapterrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AdapterRequestQuery) ForUpdate(opts ...sql.LockOption) *AdapterRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AdapterRequestQuery) ForShare(opts ...sql.LockOption) *AdapterRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AdapterRequestGroupBy is the group-by builder for AdapterRequest entities.
type AdapterRequestGroupBy struct {
	selector
	build *AdapterRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AdapterRequestGroupBy) Aggregate(fns ...AggregateFunc) *AdapterRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AdapterRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdapterRequestQuery, *AdapterRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AdapterRequestGroupBy) sqlScan(ctx context.Context, root *AdapterRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdapterRequestSelect is the builder for selecting fields of AdapterRequest entities.
type AdapterRequestSelect struct {
	*AdapterRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AdapterRequestSelect) Aggregate(fns ...AggregateFunc) *AdapterRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AdapterRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdapterRequestQuery, *AdapterRequestSelect](ctx, _s.AdapterRequestQuery, _s, _s.inters, v)
}

func (_s *AdapterRequestSelect) sqlScan(ctx context.Context, root *AdapterRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
