// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterrequest"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdapterRequestUpdate is the builder for updating AdapterRequest entities.
type AdapterRequestUpdate struct {
	config
	hooks    []Hook
	mutation *AdapterRequestMutation
}

// Where appends a list predicates to the AdapterRequestUpdate builder.
func (_u *AdapterRequestUpdate) Where(ps ...predicate.AdapterRequest) *AdapterRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AdapterRequestUpdate) SetRequestID(v string) *AdapterRequestUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableRequestID(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdapterRequestUpdate) SetUserID(v int64) *AdapterRequestUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableUserID(v *int64) *AdapterRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AdapterRequestUpdate) SetAPIKeyID(v int64) *AdapterRequestUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableAPIKeyID(v *int64) *AdapterRequestUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AdapterRequestUpdate) SetGroupID(v int64) *AdapterRequestUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableGroupID(v *int64) *AdapterRequestUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AdapterRequestUpdate) ClearGroupID() *AdapterRequestUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (_u *AdapterRequestUpdate) SetAdapterProviderID(v int64) *AdapterRequestUpdate {
	_u.mutation.SetAdapterProviderID(v)
	return _u
}

// SetNillableAdapterProviderID sets the "adapter_provider_id" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableAdapterProviderID(v *int64) *AdapterRequestUpdate {
	if v != nil {
		_u.SetAdapterProviderID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AdapterRequestUpdate) SetProvider(v string) *AdapterRequestUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableProvider(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetCapability sets the "capability" field.
func (_u *AdapterRequestUpdate) SetCapability(v string) *AdapterRequestUpdate {
	_u.mutation.SetCapability(v)
	return _u
}

// SetNillableCapability sets the "capability" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableCapability(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetCapability(*v)
	}
	return _u
}

// SetRouteTarget sets the "route_target" field.
func (_u *AdapterRequestUpdate) SetRouteTarget(v string) *AdapterRequestUpdate {
	_u.mutation.SetRouteTarget(v)
	return _u
}

// SetNillableRouteTarget sets the "route_target" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableRouteTarget(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetRouteTarget(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdapterRequestUpdate) SetMethod(v string) *AdapterRequestUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableMethod(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AdapterRequestUpdate) SetPath(v string) *AdapterRequestUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillablePath(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AdapterRequestUpdate) SetModel(v string) *AdapterRequestUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableModel(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AdapterRequestUpdate) ClearModel() *AdapterRequestUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AdapterRequestUpdate) SetStatusCode(v int) *AdapterRequestUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableStatusCode(v *int) *AdapterRequestUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AdapterRequestUpdate) AddStatusCode(v int) *AdapterRequestUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *AdapterRequestUpdate) ClearStatusCode() *AdapterRequestUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AdapterRequestUpdate) SetDurationMs(v int) *AdapterRequestUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableDurationMs(v *int) *AdapterRequestUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AdapterRequestUpdate) AddDurationMs(v int) *AdapterRequestUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AdapterRequestUpdate) ClearDurationMs() *AdapterRequestUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AdapterRequestUpdate) SetErrorMessage(v string) *AdapterRequestUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AdapterRequestUpdate) SetNillableErrorMessage(v *string) *AdapterRequestUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AdapterRequestUpdate) ClearErrorMessage() *AdapterRequestUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AdapterRequestUpdate) SetMetadata(v map[string]interface{}) *AdapterRequestUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AdapterRequestUpdate) ClearMetadata() *AdapterRequestUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AdapterRequestUpdate) SetUser(v *User) *AdapterRequestUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *AdapterRequestUpdate) SetAPIKey(v *APIKey) *AdapterRequestUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AdapterRequestUpdate) SetGroup(v *Group) *AdapterRequestUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAdapterProvider sets the "adapter_provider" edge to the AdapterProvider entity.
func (_u *AdapterRequestUpdate) SetAdapterProvider(v *AdapterProvider) *AdapterRequestUpdate {
	return _u.SetAdapterProviderID(v.ID)
}

// Mutation returns the AdapterRequestMutation object of the builder.
func (_u *AdapterRequestUpdate) Mutation() *AdapterRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AdapterRequestUpdate) ClearUser() *AdapterRequestUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *AdapterRequestUpdate) ClearAPIKey() *AdapterRequestUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AdapterRequestUpdate) ClearGroup() *AdapterRequestUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAdapterProvider clears the "adapter_provider" edge to the AdapterProvider entity.
func (_u *AdapterRequestUpdate) ClearAdapterProvider() *AdapterRequestUpdate {
	_u.mutation.ClearAdapterProvider()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdapterRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdapterRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdapterRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdapterRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdapterRequestUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adapterrequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := adapterrequest.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capability(); ok {
		if err := adapterrequest.CapabilityValidator(v); err != nil {
			return &ValidationError{Name: "capability", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.capability": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteTarget(); ok {
		if err := adapterrequest.RouteTargetValidator(v); err != nil {
			return &ValidationError{Name: "route_target", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.route_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := adapterrequest.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := adapterrequest.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := adapterrequest.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.model": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.api_key"`)
	}
	if _u.mutation.AdapterProviderCleared() && len(_u.mutation.AdapterProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.adapter_provider"`)
	}
	return nil
}

func (_u *AdapterRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adapterrequest.Table, adapterrequest.Columns, sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adapterrequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(adapterrequest.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capability(); ok {
		_spec.SetField(adapterrequest.FieldCapability, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteTarget(); ok {
		_spec.SetField(adapterrequest.FieldRouteTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adapterrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(adapterrequest.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(adapterrequest.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(adapterrequest.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(adapterrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(adapterrequest.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(adapterrequest.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(adapterrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(adapterrequest.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(adapterrequest.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(adapterrequest.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(adapterrequest.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(adapterrequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(adapterrequest.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.UserTable,
			Columns: []string{adapterrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.UserTable,
			Columns: []string{adapterrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.APIKeyTable,
			Columns: []string{adapterrequest.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.APIKeyTable,
			Columns: []string{adapterrequest.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.GroupTable,
			Columns: []string{adapterrequest.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.GroupTable,
			Columns: []string{adapterrequest.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.AdapterProviderTable,
			Columns: []string{adapterrequest.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.AdapterProviderTable,
			Columns: []string{adapterrequest.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adapterrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdapterRequestUpdateOne is the builder for updating a single AdapterRequest entity.
type AdapterRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdapterRequestMutation
}

// SetRequestID sets the "request_id" field.
func (_u *AdapterRequestUpdateOne) SetRequestID(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableRequestID(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdapterRequestUpdateOne) SetUserID(v int64) *AdapterRequestUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableUserID(v *int64) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AdapterRequestUpdateOne) SetAPIKeyID(v int64) *AdapterRequestUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableAPIKeyID(v *int64) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AdapterRequestUpdateOne) SetGroupID(v int64) *AdapterRequestUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableGroupID(v *int64) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AdapterRequestUpdateOne) ClearGroupID() *AdapterRequestUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (_u *AdapterRequestUpdateOne) SetAdapterProviderID(v int64) *AdapterRequestUpdateOne {
	_u.mutation.SetAdapterProviderID(v)
	return _u
}

// SetNillableAdapterProviderID sets the "adapter_provider_id" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableAdapterProviderID(v *int64) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetAdapterProviderID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AdapterRequestUpdateOne) SetProvider(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableProvider(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetCapability sets the "capability" field.
func (_u *AdapterRequestUpdateOne) SetCapability(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetCapability(v)
	return _u
}

// SetNillableCapability sets the "capability" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableCapability(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetCapability(*v)
	}
	return _u
}

// SetRouteTarget sets the "route_target" field.
func (_u *AdapterRequestUpdateOne) SetRouteTarget(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetRouteTarget(v)
	return _u
}

// SetNillableRouteTarget sets the "route_target" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableRouteTarget(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetRouteTarget(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdapterRequestUpdateOne) SetMethod(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableMethod(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AdapterRequestUpdateOne) SetPath(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillablePath(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AdapterRequestUpdateOne) SetModel(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableModel(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *AdapterRequestUpdateOne) ClearModel() *AdapterRequestUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AdapterRequestUpdateOne) SetStatusCode(v int) *AdapterRequestUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableStatusCode(v *int) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AdapterRequestUpdateOne) AddStatusCode(v int) *AdapterRequestUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *AdapterRequestUpdateOne) ClearStatusCode() *AdapterRequestUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AdapterRequestUpdateOne) SetDurationMs(v int) *AdapterRequestUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableDurationMs(v *int) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AdapterRequestUpdateOne) AddDurationMs(v int) *AdapterRequestUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AdapterRequestUpdateOne) ClearDurationMs() *AdapterRequestUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AdapterRequestUpdateOne) SetErrorMessage(v string) *AdapterRequestUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AdapterRequestUpdateOne) SetNillableErrorMessage(v *string) *AdapterRequestUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AdapterRequestUpdateOne) ClearErrorMessage() *AdapterRequestUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AdapterRequestUpdateOne) SetMetadata(v map[string]interface{}) *AdapterRequestUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AdapterRequestUpdateOne) ClearMetadata() *AdapterRequestUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AdapterRequestUpdateOne) SetUser(v *User) *AdapterRequestUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *AdapterRequestUpdateOne) SetAPIKey(v *APIKey) *AdapterRequestUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AdapterRequestUpdateOne) SetGroup(v *Group) *AdapterRequestUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAdapterProvider sets the "adapter_provider" edge to the AdapterProvider entity.
func (_u *AdapterRequestUpdateOne) SetAdapterProvider(v *AdapterProvider) *AdapterRequestUpdateOne {
	return _u.SetAdapterProviderID(v.ID)
}

// Mutation returns the AdapterRequestMutation object of the builder.
func (_u *AdapterRequestUpdateOne) Mutation() *AdapterRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AdapterRequestUpdateOne) ClearUser() *AdapterRequestUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *AdapterRequestUpdateOne) ClearAPIKey() *AdapterRequestUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AdapterRequestUpdateOne) ClearGroup() *AdapterRequestUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAdapterProvider clears the "adapter_provider" edge to the AdapterProvider entity.
func (_u *AdapterRequestUpdateOne) ClearAdapterProvider() *AdapterRequestUpdateOne {
	_u.mutation.ClearAdapterProvider()
	return _u
}

// Where appends a list predicates to the AdapterRequestUpdate builder.
func (_u *AdapterRequestUpdateOne) Where(ps ...predicate.AdapterRequest) *AdapterRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdapterRequestUpdateOne) Select(field string, fields ...string) *AdapterRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdapterRequest entity.
func (_u *AdapterRequestUpdateOne) Save(ctx context.Context) (*AdapterRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdapterRequestUpdateOne) SaveX(ctx context.Context) *AdapterRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdapterRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdapterRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdapterRequestUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := adapterrequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := adapterrequest.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Capability(); ok {
		if err := adapterrequest.CapabilityValidator(v); err != nil {
			return &ValidationError{Name: "capability", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.capability": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteTarget(); ok {
		if err := adapterrequest.RouteTargetValidator(v); err != nil {
			return &ValidationError{Name: "route_target", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.route_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := adapterrequest.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := adapterrequest.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := adapterrequest.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AdapterRequest.model": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.api_key"`)
	}
	if _u.mutation.AdapterProviderCleared() && len(_u.mutation.AdapterProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdapterRequest.adapter_provider"`)
	}
	return nil
}

func (_u *AdapterRequestUpdateOne) sqlSave(ctx context.Context) (_node *AdapterRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adapterrequest.Table, adapterrequest.Columns, sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdapterRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adapterrequest.FieldID)
		for _, f := range fields {
			if !adapterrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adapterrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(adapterrequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(adapterrequest.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capability(); ok {
		_spec.SetField(adapterrequest.FieldCapability, field.TypeString, value)
	}
	if value, ok := _u.mutation.RouteTarget(); ok {
		_spec.SetField(adapterrequest.FieldRouteTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adapterrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(adapterrequest.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(adapterrequest.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(adapterrequest.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(adapterrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(adapterrequest.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(adapterrequest.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(adapterrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(adapterrequest.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(adapterrequest.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(adapterrequest.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(adapterrequest.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(adapterrequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(adapterrequest.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.UserTable,
			Columns: []string{adapterrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.UserTable,
			Columns: []string{adapterrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.APIKeyTable,
			Columns: []string{adapterrequest.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.APIKeyTable,
			Columns: []string{adapterrequest.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.GroupTable,
			Columns: []string{adapterrequest.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.GroupTable,
			Columns: []string{adapterrequest.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.AdapterProviderTable,
			Columns: []string{adapterrequest.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterrequest.AdapterProviderTable,
			Columns: []string{adapterrequest.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdapterRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adapterrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
