// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterusagerecord"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/routepolicy"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdapterUsageRecordCreate is the builder for creating a AdapterUsageRecord entity.
type AdapterUsageRecordCreate struct {
	config
	mutation *AdapterUsageRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *AdapterUsageRecordCreate) SetRequestID(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AdapterUsageRecordCreate) SetUserID(v int64) *AdapterUsageRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *AdapterUsageRecordCreate) SetAPIKeyID(v int64) *AdapterUsageRecordCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AdapterUsageRecordCreate) SetGroupID(v int64) *AdapterUsageRecordCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableGroupID(v *int64) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (_c *AdapterUsageRecordCreate) SetAdapterProviderID(v int64) *AdapterUsageRecordCreate {
	_c.mutation.SetAdapterProviderID(v)
	return _c
}

// SetRoutePolicyID sets the "route_policy_id" field.
func (_c *AdapterUsageRecordCreate) SetRoutePolicyID(v int64) *AdapterUsageRecordCreate {
	_c.mutation.SetRoutePolicyID(v)
	return _c
}

// SetNillableRoutePolicyID sets the "route_policy_id" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableRoutePolicyID(v *int64) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetRoutePolicyID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AdapterUsageRecordCreate) SetProvider(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetCapability sets the "capability" field.
func (_c *AdapterUsageRecordCreate) SetCapability(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetCapability(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AdapterUsageRecordCreate) SetModel(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableModel(v *string) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AdapterUsageRecordCreate) SetMethod(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableMethod(v *string) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AdapterUsageRecordCreate) SetPath(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillablePath(v *string) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AdapterUsageRecordCreate) SetStatus(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AdapterUsageRecordCreate) SetStatusCode(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableStatusCode(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AdapterUsageRecordCreate) SetDurationMs(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableDurationMs(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AdapterUsageRecordCreate) SetErrorMessage(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableErrorMessage(v *string) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetInputUnits sets the "input_units" field.
func (_c *AdapterUsageRecordCreate) SetInputUnits(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetInputUnits(v)
	return _c
}

// SetNillableInputUnits sets the "input_units" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableInputUnits(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetInputUnits(*v)
	}
	return _c
}

// SetOutputUnits sets the "output_units" field.
func (_c *AdapterUsageRecordCreate) SetOutputUnits(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetOutputUnits(v)
	return _c
}

// SetNillableOutputUnits sets the "output_units" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableOutputUnits(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetOutputUnits(*v)
	}
	return _c
}

// SetBillableUnits sets the "billable_units" field.
func (_c *AdapterUsageRecordCreate) SetBillableUnits(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetBillableUnits(v)
	return _c
}

// SetNillableBillableUnits sets the "billable_units" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableBillableUnits(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetBillableUnits(*v)
	}
	return _c
}

// SetCostUsd sets the "cost_usd" field.
func (_c *AdapterUsageRecordCreate) SetCostUsd(v float64) *AdapterUsageRecordCreate {
	_c.mutation.SetCostUsd(v)
	return _c
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableCostUsd(v *float64) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetCostUsd(*v)
	}
	return _c
}

// SetBillableUnit sets the "billable_unit" field.
func (_c *AdapterUsageRecordCreate) SetBillableUnit(v int) *AdapterUsageRecordCreate {
	_c.mutation.SetBillableUnit(v)
	return _c
}

// SetNillableBillableUnit sets the "billable_unit" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableBillableUnit(v *int) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetBillableUnit(*v)
	}
	return _c
}

// SetBillingApplied sets the "billing_applied" field.
func (_c *AdapterUsageRecordCreate) SetBillingApplied(v bool) *AdapterUsageRecordCreate {
	_c.mutation.SetBillingApplied(v)
	return _c
}

// SetNillableBillingApplied sets the "billing_applied" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableBillingApplied(v *bool) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetBillingApplied(*v)
	}
	return _c
}

// SetBillingFingerprint sets the "billing_fingerprint" field.
func (_c *AdapterUsageRecordCreate) SetBillingFingerprint(v string) *AdapterUsageRecordCreate {
	_c.mutation.SetBillingFingerprint(v)
	return _c
}

// SetNillableBillingFingerprint sets the "billing_fingerprint" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableBillingFingerprint(v *string) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetBillingFingerprint(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AdapterUsageRecordCreate) SetMetadata(v map[string]interface{}) *AdapterUsageRecordCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdapterUsageRecordCreate) SetCreatedAt(v time.Time) *AdapterUsageRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdapterUsageRecordCreate) SetNillableCreatedAt(v *time.Time) *AdapterUsageRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AdapterUsageRecordCreate) SetUser(v *User) *AdapterUsageRecordCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *AdapterUsageRecordCreate) SetAPIKey(v *APIKey) *AdapterUsageRecordCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *AdapterUsageRecordCreate) SetGroup(v *Group) *AdapterUsageRecordCreate {
	return _c.SetGroupID(v.ID)
}

// SetAdapterProvider sets the "adapter_provider" edge to the AdapterProvider entity.
func (_c *AdapterUsageRecordCreate) SetAdapterProvider(v *AdapterProvider) *AdapterUsageRecordCreate {
	return _c.SetAdapterProviderID(v.ID)
}

// SetRoutePolicy sets the "route_policy" edge to the RoutePolicy entity.
func (_c *AdapterUsageRecordCreate) SetRoutePolicy(v *RoutePolicy) *AdapterUsageRecordCreate {
	return _c.SetRoutePolicyID(v.ID)
}

// Mutation returns the AdapterUsageRecordMutation object of the builder.
func (_c *AdapterUsageRecordCreate) Mutation() *AdapterUsageRecordMutation {
	return _c.mutation
}

// Save creates the AdapterUsageRecord in the database.
func (_c *AdapterUsageRecordCreate) Save(ctx context.Context) (*AdapterUsageRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdapterUsageRecordCreate) SaveX(ctx context.Context) *AdapterUsageRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterUsageRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterUsageRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdapterUsageRecordCreate) defaults() {
	if _, ok := _c.mutation.InputUnits(); !ok {
		v := adapterusagerecord.DefaultInputUnits
		_c.mutation.SetInputUnits(v)
	}
	if _, ok := _c.mutation.OutputUnits(); !ok {
		v := adapterusagerecord.DefaultOutputUnits
		_c.mutation.SetOutputUnits(v)
	}
	if _, ok := _c.mutation.BillableUnits(); !ok {
		v := adapterusagerecord.DefaultBillableUnits
		_c.mutation.SetBillableUnits(v)
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		v := adapterusagerecord.DefaultCostUsd
		_c.mutation.SetCostUsd(v)
	}
	if _, ok := _c.mutation.BillableUnit(); !ok {
		v := adapterusagerecord.DefaultBillableUnit
		_c.mutation.SetBillableUnit(v)
	}
	if _, ok := _c.mutation.BillingApplied(); !ok {
		v := adapterusagerecord.DefaultBillingApplied
		_c.mutation.SetBillingApplied(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adapterusagerecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdapterUsageRecordCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "AdapterUsageRecord.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := adapterusagerecord.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AdapterUsageRecord.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "AdapterUsageRecord.api_key_id"`)}
	}
	if _, ok := _c.mutation.AdapterProviderID(); !ok {
		return &ValidationError{Name: "adapter_provider_id", err: errors.New(`ent: missing required field "AdapterUsageRecord.adapter_provider_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AdapterUsageRecord.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := adapterusagerecord.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Capability(); !ok {
		return &ValidationError{Name: "capability", err: errors.New(`ent: missing required field "AdapterUsageRecord.capability"`)}
	}
	if v, ok := _c.mutation.Capability(); ok {
		if err := adapterusagerecord.CapabilityValidator(v); err != nil {
			return &ValidationError{Name: "capability", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.capability": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := adapterusagerecord.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := adapterusagerecord.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := adapterusagerecord.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AdapterUsageRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := adapterusagerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputUnits(); !ok {
		return &ValidationError{Name: "input_units", err: errors.New(`ent: missing required field "AdapterUsageRecord.input_units"`)}
	}
	if _, ok := _c.mutation.OutputUnits(); !ok {
		return &ValidationError{Name: "output_units", err: errors.New(`ent: missing required field "AdapterUsageRecord.output_units"`)}
	}
	if _, ok := _c.mutation.BillableUnits(); !ok {
		return &ValidationError{Name: "billable_units", err: errors.New(`ent: missing required field "AdapterUsageRecord.billable_units"`)}
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		return &ValidationError{Name: "cost_usd", err: errors.New(`ent: missing required field "AdapterUsageRecord.cost_usd"`)}
	}
	if _, ok := _c.mutation.BillableUnit(); !ok {
		return &ValidationError{Name: "billable_unit", err: errors.New(`ent: missing required field "AdapterUsageRecord.billable_unit"`)}
	}
	if _, ok := _c.mutation.BillingApplied(); !ok {
		return &ValidationError{Name: "billing_applied", err: errors.New(`ent: missing required field "AdapterUsageRecord.billing_applied"`)}
	}
	if v, ok := _c.mutation.BillingFingerprint(); ok {
		if err := adapterusagerecord.BillingFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "billing_fingerprint", err: fmt.Errorf(`ent: validator failed for field "AdapterUsageRecord.billing_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdapterUsageRecord.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AdapterUsageRecord.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "AdapterUsageRecord.api_key"`)}
	}
	if len(_c.mutation.AdapterProviderIDs()) == 0 {
		return &ValidationError{Name: "adapter_provider", err: errors.New(`ent: missing required edge "AdapterUsageRecord.adapter_provider"`)}
	}
	return nil
}

func (_c *AdapterUsageRecordCreate) sqlSave(ctx context.Context) (*AdapterUsageRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdapterUsageRecordCreate) createSpec() (*AdapterUsageRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &AdapterUsageRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adapterusagerecord.Table, sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(adapterusagerecord.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(adapterusagerecord.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Capability(); ok {
		_spec.SetField(adapterusagerecord.FieldCapability, field.TypeString, value)
		_node.Capability = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(adapterusagerecord.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(adapterusagerecord.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(adapterusagerecord.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(adapterusagerecord.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(adapterusagerecord.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(adapterusagerecord.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(adapterusagerecord.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.InputUnits(); ok {
		_spec.SetField(adapterusagerecord.FieldInputUnits, field.TypeInt, value)
		_node.InputUnits = value
	}
	if value, ok := _c.mutation.OutputUnits(); ok {
		_spec.SetField(adapterusagerecord.FieldOutputUnits, field.TypeInt, value)
		_node.OutputUnits = value
	}
	if value, ok := _c.mutation.BillableUnits(); ok {
		_spec.SetField(adapterusagerecord.FieldBillableUnits, field.TypeInt, value)
		_node.BillableUnits = value
	}
	if value, ok := _c.mutation.CostUsd(); ok {
		_spec.SetField(adapterusagerecord.FieldCostUsd, field.TypeFloat64, value)
		_node.CostUsd = value
	}
	if value, ok := _c.mutation.BillableUnit(); ok {
		_spec.SetField(adapterusagerecord.FieldBillableUnit, field.TypeInt, value)
		_node.BillableUnit = value
	}
	if value, ok := _c.mutation.BillingApplied(); ok {
		_spec.SetField(adapterusagerecord.FieldBillingApplied, field.TypeBool, value)
		_node.BillingApplied = value
	}
	if value, ok := _c.mutation.BillingFingerprint(); ok {
		_spec.SetField(adapterusagerecord.FieldBillingFingerprint, field.TypeString, value)
		_node.BillingFingerprint = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(adapterusagerecord.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adapterusagerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterusagerecord.UserTable,
			Columns: []string{adapterusagerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterusagerecord.APIKeyTable,
			Columns: []string{adapterusagerecord.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterusagerecord.GroupTable,
			Columns: []string{adapterusagerecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdapterProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterusagerecord.AdapterProviderTable,
			Columns: []string{adapterusagerecord.AdapterProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdapterProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoutePolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adapterusagerecord.RoutePolicyTable,
			Columns: []string{adapterusagerecord.RoutePolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoutePolicyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterUsageRecord.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterUsageRecordUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterUsageRecordCreate) OnConflict(opts ...sql.ConflictOption) *AdapterUsageRecordUpsertOne {
	_c.conflict = opts
	return &AdapterUsageRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterUsageRecordCreate) OnConflictColumns(columns ...string) *AdapterUsageRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterUsageRecordUpsertOne{
		create: _c,
	}
}

type (
	// AdapterUsageRecordUpsertOne is the builder for "upsert"-ing
	//  one AdapterUsageRecord node.
	AdapterUsageRecordUpsertOne struct {
		create *AdapterUsageRecordCreate
	}

	// AdapterUsageRecordUpsert is the "OnConflict" setter.
	AdapterUsageRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *AdapterUsageRecordUpsert) SetRequestID(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateRequestID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdapterUsageRecordUpsert) SetUserID(v int64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateUserID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterUsageRecordUpsert) SetAPIKeyID(v int64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateAPIKeyID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AdapterUsageRecordUpsert) SetGroupID(v int64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateGroupID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterUsageRecordUpsert) ClearGroupID() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldGroupID)
	return u
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterUsageRecordUpsert) SetAdapterProviderID(v int64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldAdapterProviderID, v)
	return u
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateAdapterProviderID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldAdapterProviderID)
	return u
}

// SetRoutePolicyID sets the "route_policy_id" field.
func (u *AdapterUsageRecordUpsert) SetRoutePolicyID(v int64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldRoutePolicyID, v)
	return u
}

// UpdateRoutePolicyID sets the "route_policy_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateRoutePolicyID() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldRoutePolicyID)
	return u
}

// ClearRoutePolicyID clears the value of the "route_policy_id" field.
func (u *AdapterUsageRecordUpsert) ClearRoutePolicyID() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldRoutePolicyID)
	return u
}

// SetProvider sets the "provider" field.
func (u *AdapterUsageRecordUpsert) SetProvider(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateProvider() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldProvider)
	return u
}

// SetCapability sets the "capability" field.
func (u *AdapterUsageRecordUpsert) SetCapability(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldCapability, v)
	return u
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateCapability() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldCapability)
	return u
}

// SetModel sets the "model" field.
func (u *AdapterUsageRecordUpsert) SetModel(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateModel() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AdapterUsageRecordUpsert) ClearModel() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldModel)
	return u
}

// SetMethod sets the "method" field.
func (u *AdapterUsageRecordUpsert) SetMethod(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateMethod() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldMethod)
	return u
}

// ClearMethod clears the value of the "method" field.
func (u *AdapterUsageRecordUpsert) ClearMethod() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldMethod)
	return u
}

// SetPath sets the "path" field.
func (u *AdapterUsageRecordUpsert) SetPath(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdatePath() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *AdapterUsageRecordUpsert) ClearPath() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldPath)
	return u
}

// SetStatus sets the "status" field.
func (u *AdapterUsageRecordUpsert) SetStatus(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateStatus() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldStatus)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterUsageRecordUpsert) SetStatusCode(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateStatusCode() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterUsageRecordUpsert) AddStatusCode(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterUsageRecordUpsert) ClearStatusCode() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldStatusCode)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterUsageRecordUpsert) SetDurationMs(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateDurationMs() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterUsageRecordUpsert) AddDurationMs(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterUsageRecordUpsert) ClearDurationMs() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldDurationMs)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterUsageRecordUpsert) SetErrorMessage(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateErrorMessage() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterUsageRecordUpsert) ClearErrorMessage() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldErrorMessage)
	return u
}

// SetInputUnits sets the "input_units" field.
func (u *AdapterUsageRecordUpsert) SetInputUnits(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldInputUnits, v)
	return u
}

// UpdateInputUnits sets the "input_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateInputUnits() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldInputUnits)
	return u
}

// AddInputUnits adds v to the "input_units" field.
func (u *AdapterUsageRecordUpsert) AddInputUnits(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldInputUnits, v)
	return u
}

// SetOutputUnits sets the "output_units" field.
func (u *AdapterUsageRecordUpsert) SetOutputUnits(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldOutputUnits, v)
	return u
}

// UpdateOutputUnits sets the "output_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateOutputUnits() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldOutputUnits)
	return u
}

// AddOutputUnits adds v to the "output_units" field.
func (u *AdapterUsageRecordUpsert) AddOutputUnits(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldOutputUnits, v)
	return u
}

// SetBillableUnits sets the "billable_units" field.
func (u *AdapterUsageRecordUpsert) SetBillableUnits(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldBillableUnits, v)
	return u
}

// UpdateBillableUnits sets the "billable_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateBillableUnits() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldBillableUnits)
	return u
}

// AddBillableUnits adds v to the "billable_units" field.
func (u *AdapterUsageRecordUpsert) AddBillableUnits(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldBillableUnits, v)
	return u
}

// SetCostUsd sets the "cost_usd" field.
func (u *AdapterUsageRecordUpsert) SetCostUsd(v float64) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldCostUsd, v)
	return u
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateCostUsd() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldCostUsd)
	return u
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AdapterUsageRecordUpsert) AddCostUsd(v float64) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldCostUsd, v)
	return u
}

// SetBillableUnit sets the "billable_unit" field.
func (u *AdapterUsageRecordUpsert) SetBillableUnit(v int) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldBillableUnit, v)
	return u
}

// UpdateBillableUnit sets the "billable_unit" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateBillableUnit() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldBillableUnit)
	return u
}

// AddBillableUnit adds v to the "billable_unit" field.
func (u *AdapterUsageRecordUpsert) AddBillableUnit(v int) *AdapterUsageRecordUpsert {
	u.Add(adapterusagerecord.FieldBillableUnit, v)
	return u
}

// SetBillingApplied sets the "billing_applied" field.
func (u *AdapterUsageRecordUpsert) SetBillingApplied(v bool) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldBillingApplied, v)
	return u
}

// UpdateBillingApplied sets the "billing_applied" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateBillingApplied() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldBillingApplied)
	return u
}

// SetBillingFingerprint sets the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsert) SetBillingFingerprint(v string) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldBillingFingerprint, v)
	return u
}

// UpdateBillingFingerprint sets the "billing_fingerprint" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateBillingFingerprint() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldBillingFingerprint)
	return u
}

// ClearBillingFingerprint clears the value of the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsert) ClearBillingFingerprint() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldBillingFingerprint)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *AdapterUsageRecordUpsert) SetMetadata(v map[string]interface{}) *AdapterUsageRecordUpsert {
	u.Set(adapterusagerecord.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsert) UpdateMetadata() *AdapterUsageRecordUpsert {
	u.SetExcluded(adapterusagerecord.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterUsageRecordUpsert) ClearMetadata() *AdapterUsageRecordUpsert {
	u.SetNull(adapterusagerecord.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterUsageRecordUpsertOne) UpdateNewValues() *AdapterUsageRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adapterusagerecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdapterUsageRecordUpsertOne) Ignore() *AdapterUsageRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterUsageRecordUpsertOne) DoNothing() *AdapterUsageRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterUsageRecordCreate.OnConflict
// documentation for more info.
func (u *AdapterUsageRecordUpsertOne) Update(set func(*AdapterUsageRecordUpsert)) *AdapterUsageRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterUsageRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AdapterUsageRecordUpsertOne) SetRequestID(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateRequestID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdapterUsageRecordUpsertOne) SetUserID(v int64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateUserID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterUsageRecordUpsertOne) SetAPIKeyID(v int64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateAPIKeyID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AdapterUsageRecordUpsertOne) SetGroupID(v int64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateGroupID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterUsageRecordUpsertOne) ClearGroupID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearGroupID()
	})
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterUsageRecordUpsertOne) SetAdapterProviderID(v int64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetAdapterProviderID(v)
	})
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateAdapterProviderID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateAdapterProviderID()
	})
}

// SetRoutePolicyID sets the "route_policy_id" field.
func (u *AdapterUsageRecordUpsertOne) SetRoutePolicyID(v int64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetRoutePolicyID(v)
	})
}

// UpdateRoutePolicyID sets the "route_policy_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateRoutePolicyID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateRoutePolicyID()
	})
}

// ClearRoutePolicyID clears the value of the "route_policy_id" field.
func (u *AdapterUsageRecordUpsertOne) ClearRoutePolicyID() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearRoutePolicyID()
	})
}

// SetProvider sets the "provider" field.
func (u *AdapterUsageRecordUpsertOne) SetProvider(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateProvider() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateProvider()
	})
}

// SetCapability sets the "capability" field.
func (u *AdapterUsageRecordUpsertOne) SetCapability(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetCapability(v)
	})
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateCapability() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateCapability()
	})
}

// SetModel sets the "model" field.
func (u *AdapterUsageRecordUpsertOne) SetModel(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateModel() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AdapterUsageRecordUpsertOne) ClearModel() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearModel()
	})
}

// SetMethod sets the "method" field.
func (u *AdapterUsageRecordUpsertOne) SetMethod(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateMethod() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *AdapterUsageRecordUpsertOne) ClearMethod() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearMethod()
	})
}

// SetPath sets the "path" field.
func (u *AdapterUsageRecordUpsertOne) SetPath(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdatePath() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *AdapterUsageRecordUpsertOne) ClearPath() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearPath()
	})
}

// SetStatus sets the "status" field.
func (u *AdapterUsageRecordUpsertOne) SetStatus(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateStatus() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterUsageRecordUpsertOne) SetStatusCode(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterUsageRecordUpsertOne) AddStatusCode(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateStatusCode() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterUsageRecordUpsertOne) ClearStatusCode() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterUsageRecordUpsertOne) SetDurationMs(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterUsageRecordUpsertOne) AddDurationMs(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateDurationMs() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterUsageRecordUpsertOne) ClearDurationMs() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearDurationMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterUsageRecordUpsertOne) SetErrorMessage(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateErrorMessage() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterUsageRecordUpsertOne) ClearErrorMessage() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearErrorMessage()
	})
}

// SetInputUnits sets the "input_units" field.
func (u *AdapterUsageRecordUpsertOne) SetInputUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetInputUnits(v)
	})
}

// AddInputUnits adds v to the "input_units" field.
func (u *AdapterUsageRecordUpsertOne) AddInputUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddInputUnits(v)
	})
}

// UpdateInputUnits sets the "input_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateInputUnits() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateInputUnits()
	})
}

// SetOutputUnits sets the "output_units" field.
func (u *AdapterUsageRecordUpsertOne) SetOutputUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetOutputUnits(v)
	})
}

// AddOutputUnits adds v to the "output_units" field.
func (u *AdapterUsageRecordUpsertOne) AddOutputUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddOutputUnits(v)
	})
}

// UpdateOutputUnits sets the "output_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateOutputUnits() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateOutputUnits()
	})
}

// SetBillableUnits sets the "billable_units" field.
func (u *AdapterUsageRecordUpsertOne) SetBillableUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillableUnits(v)
	})
}

// AddBillableUnits adds v to the "billable_units" field.
func (u *AdapterUsageRecordUpsertOne) AddBillableUnits(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddBillableUnits(v)
	})
}

// UpdateBillableUnits sets the "billable_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateBillableUnits() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillableUnits()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *AdapterUsageRecordUpsertOne) SetCostUsd(v float64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AdapterUsageRecordUpsertOne) AddCostUsd(v float64) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateCostUsd() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateCostUsd()
	})
}

// SetBillableUnit sets the "billable_unit" field.
func (u *AdapterUsageRecordUpsertOne) SetBillableUnit(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillableUnit(v)
	})
}

// AddBillableUnit adds v to the "billable_unit" field.
func (u *AdapterUsageRecordUpsertOne) AddBillableUnit(v int) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddBillableUnit(v)
	})
}

// UpdateBillableUnit sets the "billable_unit" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateBillableUnit() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillableUnit()
	})
}

// SetBillingApplied sets the "billing_applied" field.
func (u *AdapterUsageRecordUpsertOne) SetBillingApplied(v bool) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillingApplied(v)
	})
}

// UpdateBillingApplied sets the "billing_applied" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateBillingApplied() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillingApplied()
	})
}

// SetBillingFingerprint sets the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsertOne) SetBillingFingerprint(v string) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillingFingerprint(v)
	})
}

// UpdateBillingFingerprint sets the "billing_fingerprint" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateBillingFingerprint() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillingFingerprint()
	})
}

// ClearBillingFingerprint clears the value of the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsertOne) ClearBillingFingerprint() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearBillingFingerprint()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AdapterUsageRecordUpsertOne) SetMetadata(v map[string]interface{}) *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertOne) UpdateMetadata() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterUsageRecordUpsertOne) ClearMetadata() *AdapterUsageRecordUpsertOne {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AdapterUsageRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterUsageRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterUsageRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdapterUsageRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdapterUsageRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdapterUsageRecordCreateBulk is the builder for creating many AdapterUsageRecord entities in bulk.
type AdapterUsageRecordCreateBulk struct {
	config
	err      error
	builders []*AdapterUsageRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the AdapterUsageRecord entities in the database.
func (_c *AdapterUsageRecordCreateBulk) Save(ctx context.Context) ([]*AdapterUsageRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdapterUsageRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdapterUsageRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdapterUsageRecordCreateBulk) SaveX(ctx context.Context) []*AdapterUsageRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdapterUsageRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdapterUsageRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdapterUsageRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdapterUsageRecordUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdapterUsageRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdapterUsageRecordUpsertBulk {
	_c.conflict = opts
	return &AdapterUsageRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdapterUsageRecordCreateBulk) OnConflictColumns(columns ...string) *AdapterUsageRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdapterUsageRecordUpsertBulk{
		create: _c,
	}
}

// AdapterUsageRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of AdapterUsageRecord nodes.
type AdapterUsageRecordUpsertBulk struct {
	create *AdapterUsageRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdapterUsageRecordUpsertBulk) UpdateNewValues() *AdapterUsageRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adapterusagerecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdapterUsageRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdapterUsageRecordUpsertBulk) Ignore() *AdapterUsageRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdapterUsageRecordUpsertBulk) DoNothing() *AdapterUsageRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdapterUsageRecordCreateBulk.OnConflict
// documentation for more info.
func (u *AdapterUsageRecordUpsertBulk) Update(set func(*AdapterUsageRecordUpsert)) *AdapterUsageRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdapterUsageRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetRequestID(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateRequestID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetUserID(v int64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateUserID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetAPIKeyID(v int64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateAPIKeyID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetGroupID(v int64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateGroupID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *AdapterUsageRecordUpsertBulk) ClearGroupID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearGroupID()
	})
}

// SetAdapterProviderID sets the "adapter_provider_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetAdapterProviderID(v int64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetAdapterProviderID(v)
	})
}

// UpdateAdapterProviderID sets the "adapter_provider_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateAdapterProviderID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateAdapterProviderID()
	})
}

// SetRoutePolicyID sets the "route_policy_id" field.
func (u *AdapterUsageRecordUpsertBulk) SetRoutePolicyID(v int64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetRoutePolicyID(v)
	})
}

// UpdateRoutePolicyID sets the "route_policy_id" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateRoutePolicyID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateRoutePolicyID()
	})
}

// ClearRoutePolicyID clears the value of the "route_policy_id" field.
func (u *AdapterUsageRecordUpsertBulk) ClearRoutePolicyID() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearRoutePolicyID()
	})
}

// SetProvider sets the "provider" field.
func (u *AdapterUsageRecordUpsertBulk) SetProvider(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateProvider() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateProvider()
	})
}

// SetCapability sets the "capability" field.
func (u *AdapterUsageRecordUpsertBulk) SetCapability(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetCapability(v)
	})
}

// UpdateCapability sets the "capability" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateCapability() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateCapability()
	})
}

// SetModel sets the "model" field.
func (u *AdapterUsageRecordUpsertBulk) SetModel(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateModel() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AdapterUsageRecordUpsertBulk) ClearModel() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearModel()
	})
}

// SetMethod sets the "method" field.
func (u *AdapterUsageRecordUpsertBulk) SetMethod(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateMethod() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *AdapterUsageRecordUpsertBulk) ClearMethod() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearMethod()
	})
}

// SetPath sets the "path" field.
func (u *AdapterUsageRecordUpsertBulk) SetPath(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdatePath() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *AdapterUsageRecordUpsertBulk) ClearPath() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearPath()
	})
}

// SetStatus sets the "status" field.
func (u *AdapterUsageRecordUpsertBulk) SetStatus(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateStatus() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AdapterUsageRecordUpsertBulk) SetStatusCode(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AdapterUsageRecordUpsertBulk) AddStatusCode(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateStatusCode() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AdapterUsageRecordUpsertBulk) ClearStatusCode() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AdapterUsageRecordUpsertBulk) SetDurationMs(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AdapterUsageRecordUpsertBulk) AddDurationMs(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateDurationMs() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AdapterUsageRecordUpsertBulk) ClearDurationMs() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearDurationMs()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *AdapterUsageRecordUpsertBulk) SetErrorMessage(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateErrorMessage() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *AdapterUsageRecordUpsertBulk) ClearErrorMessage() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearErrorMessage()
	})
}

// SetInputUnits sets the "input_units" field.
func (u *AdapterUsageRecordUpsertBulk) SetInputUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetInputUnits(v)
	})
}

// AddInputUnits adds v to the "input_units" field.
func (u *AdapterUsageRecordUpsertBulk) AddInputUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddInputUnits(v)
	})
}

// UpdateInputUnits sets the "input_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateInputUnits() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateInputUnits()
	})
}

// SetOutputUnits sets the "output_units" field.
func (u *AdapterUsageRecordUpsertBulk) SetOutputUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetOutputUnits(v)
	})
}

// AddOutputUnits adds v to the "output_units" field.
func (u *AdapterUsageRecordUpsertBulk) AddOutputUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddOutputUnits(v)
	})
}

// UpdateOutputUnits sets the "output_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateOutputUnits() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateOutputUnits()
	})
}

// SetBillableUnits sets the "billable_units" field.
func (u *AdapterUsageRecordUpsertBulk) SetBillableUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillableUnits(v)
	})
}

// AddBillableUnits adds v to the "billable_units" field.
func (u *AdapterUsageRecordUpsertBulk) AddBillableUnits(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddBillableUnits(v)
	})
}

// UpdateBillableUnits sets the "billable_units" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateBillableUnits() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillableUnits()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *AdapterUsageRecordUpsertBulk) SetCostUsd(v float64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *AdapterUsageRecordUpsertBulk) AddCostUsd(v float64) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateCostUsd() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateCostUsd()
	})
}

// SetBillableUnit sets the "billable_unit" field.
func (u *AdapterUsageRecordUpsertBulk) SetBillableUnit(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillableUnit(v)
	})
}

// AddBillableUnit adds v to the "billable_unit" field.
func (u *AdapterUsageRecordUpsertBulk) AddBillableUnit(v int) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.AddBillableUnit(v)
	})
}

// UpdateBillableUnit sets the "billable_unit" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateBillableUnit() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillableUnit()
	})
}

// SetBillingApplied sets the "billing_applied" field.
func (u *AdapterUsageRecordUpsertBulk) SetBillingApplied(v bool) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillingApplied(v)
	})
}

// UpdateBillingApplied sets the "billing_applied" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateBillingApplied() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillingApplied()
	})
}

// SetBillingFingerprint sets the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsertBulk) SetBillingFingerprint(v string) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetBillingFingerprint(v)
	})
}

// UpdateBillingFingerprint sets the "billing_fingerprint" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateBillingFingerprint() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateBillingFingerprint()
	})
}

// ClearBillingFingerprint clears the value of the "billing_fingerprint" field.
func (u *AdapterUsageRecordUpsertBulk) ClearBillingFingerprint() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearBillingFingerprint()
	})
}

// SetMetadata sets the "metadata" field.
func (u *AdapterUsageRecordUpsertBulk) SetMetadata(v map[string]interface{}) *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *AdapterUsageRecordUpsertBulk) UpdateMetadata() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *AdapterUsageRecordUpsertBulk) ClearMetadata() *AdapterUsageRecordUpsertBulk {
	return u.Update(func(s *AdapterUsageRecordUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *AdapterUsageRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdapterUsageRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdapterUsageRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdapterUsageRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
