// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
)

// AdapterProvider is the model entity for the AdapterProvider schema.
type AdapterProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AdapterType holds the value of the "adapter_type" field.
	AdapterType string `json:"adapter_type,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// AuthMode holds the value of the "auth_mode" field.
	AuthMode *string `json:"auth_mode,omitempty"`
	// Credentials holds the value of the "credentials" field.
	Credentials map[string]string `json:"credentials,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities []string `json:"capabilities,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// TimeoutMs holds the value of the "timeout_ms" field.
	TimeoutMs int `json:"timeout_ms,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra map[string]interface{} `json:"extra,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdapterProviderQuery when eager-loading is set.
	Edges        AdapterProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdapterProviderEdges holds the relations/edges for other nodes in the graph.
type AdapterProviderEdges struct {
	// RoutePolicies holds the value of the route_policies edge.
	RoutePolicies []*RoutePolicy `json:"route_policies,omitempty"`
	// AdapterRequests holds the value of the adapter_requests edge.
	AdapterRequests []*AdapterRequest `json:"adapter_requests,omitempty"`
	// AdapterUsageRecords holds the value of the adapter_usage_records edge.
	AdapterUsageRecords []*AdapterUsageRecord `json:"adapter_usage_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RoutePoliciesOrErr returns the RoutePolicies value or an error if the edge
// was not loaded in eager-loading.
func (e AdapterProviderEdges) RoutePoliciesOrErr() ([]*RoutePolicy, error) {
	if e.loadedTypes[0] {
		return e.RoutePolicies, nil
	}
	return nil, &NotLoadedError{edge: "route_policies"}
}

// AdapterRequestsOrErr returns the AdapterRequests value or an error if the edge
// was not loaded in eager-loading.
func (e AdapterProviderEdges) AdapterRequestsOrErr() ([]*AdapterRequest, error) {
	if e.loadedTypes[1] {
		return e.AdapterRequests, nil
	}
	return nil, &NotLoadedError{edge: "adapter_requests"}
}

// AdapterUsageRecordsOrErr returns the AdapterUsageRecords value or an error if the edge
// was not loaded in eager-loading.
func (e AdapterProviderEdges) AdapterUsageRecordsOrErr() ([]*AdapterUsageRecord, error) {
	if e.loadedTypes[2] {
		return e.AdapterUsageRecords, nil
	}
	return nil, &NotLoadedError{edge: "adapter_usage_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdapterProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adapterprovider.FieldCredentials, adapterprovider.FieldCapabilities, adapterprovider.FieldExtra:
			values[i] = new([]byte)
		case adapterprovider.FieldID, adapterprovider.FieldPriority, adapterprovider.FieldTimeoutMs:
			values[i] = new(sql.NullInt64)
		case adapterprovider.FieldName, adapterprovider.FieldSlug, adapterprovider.FieldStatus, adapterprovider.FieldAdapterType, adapterprovider.FieldBaseURL, adapterprovider.FieldAuthMode:
			values[i] = new(sql.NullString)
		case adapterprovider.FieldCreatedAt, adapterprovider.FieldUpdatedAt, adapterprovider.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdapterProvider fields.
func (_m *AdapterProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adapterprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adapterprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adapterprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adapterprovider.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case adapterprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case adapterprovider.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case adapterprovider.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case adapterprovider.FieldAdapterType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter_type", values[i])
			} else if value.Valid {
				_m.AdapterType = value.String
			}
		case adapterprovider.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case adapterprovider.FieldAuthMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_mode", values[i])
			} else if value.Valid {
				_m.AuthMode = new(string)
				*_m.AuthMode = value.String
			}
		case adapterprovider.FieldCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Credentials); err != nil {
					return fmt.Errorf("unmarshal field credentials: %w", err)
				}
			}
		case adapterprovider.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case adapterprovider.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case adapterprovider.FieldTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_ms", values[i])
			} else if value.Valid {
				_m.TimeoutMs = int(value.Int64)
			}
		case adapterprovider.FieldExtra:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Extra); err != nil {
					return fmt.Errorf("unmarshal field extra: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdapterProvider.
// This includes values selected through modifiers, order, etc.
func (_m *AdapterProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoutePolicies queries the "route_policies" edge of the AdapterProvider entity.
func (_m *AdapterProvider) QueryRoutePolicies() *RoutePolicyQuery {
	return NewAdapterProviderClient(_m.config).QueryRoutePolicies(_m)
}

// QueryAdapterRequests queries the "adapter_requests" edge of the AdapterProvider entity.
func (_m *AdapterProvider) QueryAdapterRequests() *AdapterRequestQuery {
	return NewAdapterProviderClient(_m.config).QueryAdapterRequests(_m)
}

// QueryAdapterUsageRecords queries the "adapter_usage_records" edge of the AdapterProvider entity.
func (_m *AdapterProvider) QueryAdapterUsageRecords() *AdapterUsageRecordQuery {
	return NewAdapterProviderClient(_m.config).QueryAdapterUsageRecords(_m)
}

// Update returns a builder for updating this AdapterProvider.
// Note that you need to call AdapterProvider.Unwrap() before calling this method if this AdapterProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdapterProvider) Update() *AdapterProviderUpdateOne {
	return NewAdapterProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdapterProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdapterProvider) Unwrap() *AdapterProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdapterProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdapterProvider) String() string {
	var builder strings.Builder
	builder.WriteString("AdapterProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("adapter_type=")
	builder.WriteString(_m.AdapterType)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	if v := _m.AuthMode; v != nil {
		builder.WriteString("auth_mode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("credentials=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credentials))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(fmt.Sprintf("%v", _m.Extra))
	builder.WriteByte(')')
	return builder.String()
}

// AdapterProviders is a parsable slice of AdapterProvider.
type AdapterProviders []*AdapterProvider
