// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterrequest"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdapterRequest is the model entity for the AdapterRequest schema.
type AdapterRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AdapterProviderID holds the value of the "adapter_provider_id" field.
	AdapterProviderID int64 `json:"adapter_provider_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Capability holds the value of the "capability" field.
	Capability string `json:"capability,omitempty"`
	// RouteTarget holds the value of the "route_target" field.
	RouteTarget string `json:"route_target,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Model holds the value of the "model" field.
	Model *string `json:"model,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int `json:"duration_ms,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdapterRequestQuery when eager-loading is set.
	Edges        AdapterRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdapterRequestEdges holds the relations/edges for other nodes in the graph.
type AdapterRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// AdapterProvider holds the value of the adapter_provider edge.
	AdapterProvider *AdapterProvider `json:"adapter_provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterRequestEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterRequestEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// AdapterProviderOrErr returns the AdapterProvider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdapterRequestEdges) AdapterProviderOrErr() (*AdapterProvider, error) {
	if e.AdapterProvider != nil {
		return e.AdapterProvider, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: adapterprovider.Label}
	}
	return nil, &NotLoadedError{edge: "adapter_provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdapterRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adapterrequest.FieldMetadata:
			values[i] = new([]byte)
		case adapterrequest.FieldID, adapterrequest.FieldUserID, adapterrequest.FieldAPIKeyID, adapterrequest.FieldGroupID, adapterrequest.FieldAdapterProviderID, adapterrequest.FieldStatusCode, adapterrequest.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case adapterrequest.FieldRequestID, adapterrequest.FieldProvider, adapterrequest.FieldCapability, adapterrequest.FieldRouteTarget, adapterrequest.FieldMethod, adapterrequest.FieldPath, adapterrequest.FieldModel, adapterrequest.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case adapterrequest.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdapterRequest fields.
func (_m *AdapterRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adapterrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adapterrequest.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case adapterrequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case adapterrequest.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case adapterrequest.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case adapterrequest.FieldAdapterProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field adapter_provider_id", values[i])
			} else if value.Valid {
				_m.AdapterProviderID = value.Int64
			}
		case adapterrequest.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case adapterrequest.FieldCapability:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field capability", values[i])
			} else if value.Valid {
				_m.Capability = value.String
			}
		case adapterrequest.FieldRouteTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_target", values[i])
			} else if value.Valid {
				_m.RouteTarget = value.String
			}
		case adapterrequest.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case adapterrequest.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case adapterrequest.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case adapterrequest.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case adapterrequest.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case adapterrequest.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case adapterrequest.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case adapterrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdapterRequest.
// This includes values selected through modifiers, order, etc.
func (_m *AdapterRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the AdapterRequest entity.
func (_m *AdapterRequest) QueryUser() *UserQuery {
	return NewAdapterRequestClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the AdapterRequest entity.
func (_m *AdapterRequest) QueryAPIKey() *APIKeyQuery {
	return NewAdapterRequestClient(_m.config).QueryAPIKey(_m)
}

// QueryGroup queries the "group" edge of the AdapterRequest entity.
func (_m *AdapterRequest) QueryGroup() *GroupQuery {
	return NewAdapterRequestClient(_m.config).QueryGroup(_m)
}

// QueryAdapterProvider queries the "adapter_provider" edge of the AdapterRequest entity.
func (_m *AdapterRequest) QueryAdapterProvider() *AdapterProviderQuery {
	return NewAdapterRequestClient(_m.config).QueryAdapterProvider(_m)
}

// Update returns a builder for updating this AdapterRequest.
// Note that you need to call AdapterRequest.Unwrap() before calling this method if this AdapterRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdapterRequest) Update() *AdapterRequestUpdateOne {
	return NewAdapterRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdapterRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdapterRequest) Unwrap() *AdapterRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdapterRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdapterRequest) String() string {
	var builder strings.Builder
	builder.WriteString("AdapterRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("adapter_provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdapterProviderID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("capability=")
	builder.WriteString(_m.Capability)
	builder.WriteString(", ")
	builder.WriteString("route_target=")
	builder.WriteString(_m.RouteTarget)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdapterRequests is a parsable slice of AdapterRequest.
type AdapterRequests []*AdapterRequest
