// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adapterprovider"
	"github.com/Wei-Shaw/sub2api/ent/adapterrequest"
	"github.com/Wei-Shaw/sub2api/ent/adapterusagerecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/routepolicy"
)

// AdapterProviderUpdate is the builder for updating AdapterProvider entities.
type AdapterProviderUpdate struct {
	config
	hooks    []Hook
	mutation *AdapterProviderMutation
}

// Where appends a list predicates to the AdapterProviderUpdate builder.
func (_u *AdapterProviderUpdate) Where(ps ...predicate.AdapterProvider) *AdapterProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdapterProviderUpdate) SetUpdatedAt(v time.Time) *AdapterProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdapterProviderUpdate) SetDeletedAt(v time.Time) *AdapterProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableDeletedAt(v *time.Time) *AdapterProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdapterProviderUpdate) ClearDeletedAt() *AdapterProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AdapterProviderUpdate) SetName(v string) *AdapterProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableName(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AdapterProviderUpdate) SetSlug(v string) *AdapterProviderUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableSlug(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AdapterProviderUpdate) SetStatus(v string) *AdapterProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableStatus(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdapterType sets the "adapter_type" field.
func (_u *AdapterProviderUpdate) SetAdapterType(v string) *AdapterProviderUpdate {
	_u.mutation.SetAdapterType(v)
	return _u
}

// SetNillableAdapterType sets the "adapter_type" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableAdapterType(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetAdapterType(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AdapterProviderUpdate) SetBaseURL(v string) *AdapterProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableBaseURL(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *AdapterProviderUpdate) SetAuthMode(v string) *AdapterProviderUpdate {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableAuthMode(v *string) *AdapterProviderUpdate {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// ClearAuthMode clears the value of the "auth_mode" field.
func (_u *AdapterProviderUpdate) ClearAuthMode() *AdapterProviderUpdate {
	_u.mutation.ClearAuthMode()
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *AdapterProviderUpdate) SetCredentials(v map[string]string) *AdapterProviderUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// ClearCredentials clears the value of the "credentials" field.
func (_u *AdapterProviderUpdate) ClearCredentials() *AdapterProviderUpdate {
	_u.mutation.ClearCredentials()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *AdapterProviderUpdate) SetCapabilities(v []string) *AdapterProviderUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *AdapterProviderUpdate) AppendCapabilities(v []string) *AdapterProviderUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *AdapterProviderUpdate) ClearCapabilities() *AdapterProviderUpdate {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AdapterProviderUpdate) SetPriority(v int) *AdapterProviderUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillablePriority(v *int) *AdapterProviderUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AdapterProviderUpdate) AddPriority(v int) *AdapterProviderUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *AdapterProviderUpdate) SetTimeoutMs(v int) *AdapterProviderUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *AdapterProviderUpdate) SetNillableTimeoutMs(v *int) *AdapterProviderUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *AdapterProviderUpdate) AddTimeoutMs(v int) *AdapterProviderUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetExtra sets the "extra" field.
func (_u *AdapterProviderUpdate) SetExtra(v map[string]interface{}) *AdapterProviderUpdate {
	_u.mutation.SetExtra(v)
	return _u
}

// ClearExtra clears the value of the "extra" field.
func (_u *AdapterProviderUpdate) ClearExtra() *AdapterProviderUpdate {
	_u.mutation.ClearExtra()
	return _u
}

// AddRoutePolicyIDs adds the "route_policies" edge to the RoutePolicy entity by IDs.
func (_u *AdapterProviderUpdate) AddRoutePolicyIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.AddRoutePolicyIDs(ids...)
	return _u
}

// AddRoutePolicies adds the "route_policies" edges to the RoutePolicy entity.
func (_u *AdapterProviderUpdate) AddRoutePolicies(v ...*RoutePolicy) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoutePolicyIDs(ids...)
}

// AddAdapterRequestIDs adds the "adapter_requests" edge to the AdapterRequest entity by IDs.
func (_u *AdapterProviderUpdate) AddAdapterRequestIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.AddAdapterRequestIDs(ids...)
	return _u
}

// AddAdapterRequests adds the "adapter_requests" edges to the AdapterRequest entity.
func (_u *AdapterProviderUpdate) AddAdapterRequests(v ...*AdapterRequest) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdapterRequestIDs(ids...)
}

// AddAdapterUsageRecordIDs adds the "adapter_usage_records" edge to the AdapterUsageRecord entity by IDs.
func (_u *AdapterProviderUpdate) AddAdapterUsageRecordIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.AddAdapterUsageRecordIDs(ids...)
	return _u
}

// AddAdapterUsageRecords adds the "adapter_usage_records" edges to the AdapterUsageRecord entity.
func (_u *AdapterProviderUpdate) AddAdapterUsageRecords(v ...*AdapterUsageRecord) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdapterUsageRecordIDs(ids...)
}

// Mutation returns the AdapterProviderMutation object of the builder.
func (_u *AdapterProviderUpdate) Mutation() *AdapterProviderMutation {
	return _u.mutation
}

// ClearRoutePolicies clears all "route_policies" edges to the RoutePolicy entity.
func (_u *AdapterProviderUpdate) ClearRoutePolicies() *AdapterProviderUpdate {
	_u.mutation.ClearRoutePolicies()
	return _u
}

// RemoveRoutePolicyIDs removes the "route_policies" edge to RoutePolicy entities by IDs.
func (_u *AdapterProviderUpdate) RemoveRoutePolicyIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.RemoveRoutePolicyIDs(ids...)
	return _u
}

// RemoveRoutePolicies removes "route_policies" edges to RoutePolicy entities.
func (_u *AdapterProviderUpdate) RemoveRoutePolicies(v ...*RoutePolicy) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoutePolicyIDs(ids...)
}

// ClearAdapterRequests clears all "adapter_requests" edges to the AdapterRequest entity.
func (_u *AdapterProviderUpdate) ClearAdapterRequests() *AdapterProviderUpdate {
	_u.mutation.ClearAdapterRequests()
	return _u
}

// RemoveAdapterRequestIDs removes the "adapter_requests" edge to AdapterRequest entities by IDs.
func (_u *AdapterProviderUpdate) RemoveAdapterRequestIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.RemoveAdapterRequestIDs(ids...)
	return _u
}

// RemoveAdapterRequests removes "adapter_requests" edges to AdapterRequest entities.
func (_u *AdapterProviderUpdate) RemoveAdapterRequests(v ...*AdapterRequest) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdapterRequestIDs(ids...)
}

// ClearAdapterUsageRecords clears all "adapter_usage_records" edges to the AdapterUsageRecord entity.
func (_u *AdapterProviderUpdate) ClearAdapterUsageRecords() *AdapterProviderUpdate {
	_u.mutation.ClearAdapterUsageRecords()
	return _u
}

// RemoveAdapterUsageRecordIDs removes the "adapter_usage_records" edge to AdapterUsageRecord entities by IDs.
func (_u *AdapterProviderUpdate) RemoveAdapterUsageRecordIDs(ids ...int64) *AdapterProviderUpdate {
	_u.mutation.RemoveAdapterUsageRecordIDs(ids...)
	return _u
}

// RemoveAdapterUsageRecords removes "adapter_usage_records" edges to AdapterUsageRecord entities.
func (_u *AdapterProviderUpdate) RemoveAdapterUsageRecords(v ...*AdapterUsageRecord) *AdapterProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdapterUsageRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdapterProviderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdapterProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdapterProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdapterProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdapterProviderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adapterprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adapterprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adapterprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdapterProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adapterprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := adapterprovider.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := adapterprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdapterType(); ok {
		if err := adapterprovider.AdapterTypeValidator(v); err != nil {
			return &ValidationError{Name: "adapter_type", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.adapter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := adapterprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := adapterprovider.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.auth_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *AdapterProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adapterprovider.Table, adapterprovider.Columns, sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adapterprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adapterprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adapterprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adapterprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(adapterprovider.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(adapterprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdapterType(); ok {
		_spec.SetField(adapterprovider.FieldAdapterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(adapterprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(adapterprovider.FieldAuthMode, field.TypeString, value)
	}
	if _u.mutation.AuthModeCleared() {
		_spec.ClearField(adapterprovider.FieldAuthMode, field.TypeString)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(adapterprovider.FieldCredentials, field.TypeJSON, value)
	}
	if _u.mutation.CredentialsCleared() {
		_spec.ClearField(adapterprovider.FieldCredentials, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(adapterprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adapterprovider.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(adapterprovider.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(adapterprovider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(adapterprovider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(adapterprovider.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(adapterprovider.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(adapterprovider.FieldExtra, field.TypeJSON, value)
	}
	if _u.mutation.ExtraCleared() {
		_spec.ClearField(adapterprovider.FieldExtra, field.TypeJSON)
	}
	if _u.mutation.RoutePoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutePoliciesIDs(); len(nodes) > 0 && !_u.mutation.RoutePoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutePoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdapterRequestsIDs(); len(nodes) > 0 && !_u.mutation.AdapterRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterUsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdapterUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.AdapterUsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterUsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adapterprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdapterProviderUpdateOne is the builder for updating a single AdapterProvider entity.
type AdapterProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdapterProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdapterProviderUpdateOne) SetUpdatedAt(v time.Time) *AdapterProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdapterProviderUpdateOne) SetDeletedAt(v time.Time) *AdapterProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdapterProviderUpdateOne) ClearDeletedAt() *AdapterProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AdapterProviderUpdateOne) SetName(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableName(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *AdapterProviderUpdateOne) SetSlug(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableSlug(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AdapterProviderUpdateOne) SetStatus(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableStatus(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdapterType sets the "adapter_type" field.
func (_u *AdapterProviderUpdateOne) SetAdapterType(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetAdapterType(v)
	return _u
}

// SetNillableAdapterType sets the "adapter_type" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableAdapterType(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetAdapterType(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AdapterProviderUpdateOne) SetBaseURL(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableBaseURL(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *AdapterProviderUpdateOne) SetAuthMode(v string) *AdapterProviderUpdateOne {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableAuthMode(v *string) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// ClearAuthMode clears the value of the "auth_mode" field.
func (_u *AdapterProviderUpdateOne) ClearAuthMode() *AdapterProviderUpdateOne {
	_u.mutation.ClearAuthMode()
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *AdapterProviderUpdateOne) SetCredentials(v map[string]string) *AdapterProviderUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// ClearCredentials clears the value of the "credentials" field.
func (_u *AdapterProviderUpdateOne) ClearCredentials() *AdapterProviderUpdateOne {
	_u.mutation.ClearCredentials()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *AdapterProviderUpdateOne) SetCapabilities(v []string) *AdapterProviderUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *AdapterProviderUpdateOne) AppendCapabilities(v []string) *AdapterProviderUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *AdapterProviderUpdateOne) ClearCapabilities() *AdapterProviderUpdateOne {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AdapterProviderUpdateOne) SetPriority(v int) *AdapterProviderUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillablePriority(v *int) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AdapterProviderUpdateOne) AddPriority(v int) *AdapterProviderUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *AdapterProviderUpdateOne) SetTimeoutMs(v int) *AdapterProviderUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *AdapterProviderUpdateOne) SetNillableTimeoutMs(v *int) *AdapterProviderUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *AdapterProviderUpdateOne) AddTimeoutMs(v int) *AdapterProviderUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetExtra sets the "extra" field.
func (_u *AdapterProviderUpdateOne) SetExtra(v map[string]interface{}) *AdapterProviderUpdateOne {
	_u.mutation.SetExtra(v)
	return _u
}

// ClearExtra clears the value of the "extra" field.
func (_u *AdapterProviderUpdateOne) ClearExtra() *AdapterProviderUpdateOne {
	_u.mutation.ClearExtra()
	return _u
}

// AddRoutePolicyIDs adds the "route_policies" edge to the RoutePolicy entity by IDs.
func (_u *AdapterProviderUpdateOne) AddRoutePolicyIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.AddRoutePolicyIDs(ids...)
	return _u
}

// AddRoutePolicies adds the "route_policies" edges to the RoutePolicy entity.
func (_u *AdapterProviderUpdateOne) AddRoutePolicies(v ...*RoutePolicy) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoutePolicyIDs(ids...)
}

// AddAdapterRequestIDs adds the "adapter_requests" edge to the AdapterRequest entity by IDs.
func (_u *AdapterProviderUpdateOne) AddAdapterRequestIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.AddAdapterRequestIDs(ids...)
	return _u
}

// AddAdapterRequests adds the "adapter_requests" edges to the AdapterRequest entity.
func (_u *AdapterProviderUpdateOne) AddAdapterRequests(v ...*AdapterRequest) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdapterRequestIDs(ids...)
}

// AddAdapterUsageRecordIDs adds the "adapter_usage_records" edge to the AdapterUsageRecord entity by IDs.
func (_u *AdapterProviderUpdateOne) AddAdapterUsageRecordIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.AddAdapterUsageRecordIDs(ids...)
	return _u
}

// AddAdapterUsageRecords adds the "adapter_usage_records" edges to the AdapterUsageRecord entity.
func (_u *AdapterProviderUpdateOne) AddAdapterUsageRecords(v ...*AdapterUsageRecord) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdapterUsageRecordIDs(ids...)
}

// Mutation returns the AdapterProviderMutation object of the builder.
func (_u *AdapterProviderUpdateOne) Mutation() *AdapterProviderMutation {
	return _u.mutation
}

// ClearRoutePolicies clears all "route_policies" edges to the RoutePolicy entity.
func (_u *AdapterProviderUpdateOne) ClearRoutePolicies() *AdapterProviderUpdateOne {
	_u.mutation.ClearRoutePolicies()
	return _u
}

// RemoveRoutePolicyIDs removes the "route_policies" edge to RoutePolicy entities by IDs.
func (_u *AdapterProviderUpdateOne) RemoveRoutePolicyIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.RemoveRoutePolicyIDs(ids...)
	return _u
}

// RemoveRoutePolicies removes "route_policies" edges to RoutePolicy entities.
func (_u *AdapterProviderUpdateOne) RemoveRoutePolicies(v ...*RoutePolicy) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoutePolicyIDs(ids...)
}

// ClearAdapterRequests clears all "adapter_requests" edges to the AdapterRequest entity.
func (_u *AdapterProviderUpdateOne) ClearAdapterRequests() *AdapterProviderUpdateOne {
	_u.mutation.ClearAdapterRequests()
	return _u
}

// RemoveAdapterRequestIDs removes the "adapter_requests" edge to AdapterRequest entities by IDs.
func (_u *AdapterProviderUpdateOne) RemoveAdapterRequestIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.RemoveAdapterRequestIDs(ids...)
	return _u
}

// RemoveAdapterRequests removes "adapter_requests" edges to AdapterRequest entities.
func (_u *AdapterProviderUpdateOne) RemoveAdapterRequests(v ...*AdapterRequest) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdapterRequestIDs(ids...)
}

// ClearAdapterUsageRecords clears all "adapter_usage_records" edges to the AdapterUsageRecord entity.
func (_u *AdapterProviderUpdateOne) ClearAdapterUsageRecords() *AdapterProviderUpdateOne {
	_u.mutation.ClearAdapterUsageRecords()
	return _u
}

// RemoveAdapterUsageRecordIDs removes the "adapter_usage_records" edge to AdapterUsageRecord entities by IDs.
func (_u *AdapterProviderUpdateOne) RemoveAdapterUsageRecordIDs(ids ...int64) *AdapterProviderUpdateOne {
	_u.mutation.RemoveAdapterUsageRecordIDs(ids...)
	return _u
}

// RemoveAdapterUsageRecords removes "adapter_usage_records" edges to AdapterUsageRecord entities.
func (_u *AdapterProviderUpdateOne) RemoveAdapterUsageRecords(v ...*AdapterUsageRecord) *AdapterProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdapterUsageRecordIDs(ids...)
}

// Where appends a list predicates to the AdapterProviderUpdate builder.
func (_u *AdapterProviderUpdateOne) Where(ps ...predicate.AdapterProvider) *AdapterProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdapterProviderUpdateOne) Select(field string, fields ...string) *AdapterProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdapterProvider entity.
func (_u *AdapterProviderUpdateOne) Save(ctx context.Context) (*AdapterProvider, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdapterProviderUpdateOne) SaveX(ctx context.Context) *AdapterProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdapterProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdapterProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdapterProviderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adapterprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adapterprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adapterprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdapterProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adapterprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := adapterprovider.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := adapterprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdapterType(); ok {
		if err := adapterprovider.AdapterTypeValidator(v); err != nil {
			return &ValidationError{Name: "adapter_type", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.adapter_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := adapterprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := adapterprovider.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "AdapterProvider.auth_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *AdapterProviderUpdateOne) sqlSave(ctx context.Context) (_node *AdapterProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adapterprovider.Table, adapterprovider.Columns, sqlgraph.NewFieldSpec(adapterprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdapterProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adapterprovider.FieldID)
		for _, f := range fields {
			if !adapterprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adapterprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adapterprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adapterprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adapterprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adapterprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(adapterprovider.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(adapterprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdapterType(); ok {
		_spec.SetField(adapterprovider.FieldAdapterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(adapterprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(adapterprovider.FieldAuthMode, field.TypeString, value)
	}
	if _u.mutation.AuthModeCleared() {
		_spec.ClearField(adapterprovider.FieldAuthMode, field.TypeString)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(adapterprovider.FieldCredentials, field.TypeJSON, value)
	}
	if _u.mutation.CredentialsCleared() {
		_spec.ClearField(adapterprovider.FieldCredentials, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(adapterprovider.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adapterprovider.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(adapterprovider.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(adapterprovider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(adapterprovider.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(adapterprovider.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(adapterprovider.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(adapterprovider.FieldExtra, field.TypeJSON, value)
	}
	if _u.mutation.ExtraCleared() {
		_spec.ClearField(adapterprovider.FieldExtra, field.TypeJSON)
	}
	if _u.mutation.RoutePoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutePoliciesIDs(); len(nodes) > 0 && !_u.mutation.RoutePoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutePoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.RoutePoliciesTable,
			Columns: []string{adapterprovider.RoutePoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepolicy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdapterRequestsIDs(); len(nodes) > 0 && !_u.mutation.AdapterRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterRequestsTable,
			Columns: []string{adapterprovider.AdapterRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterrequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdapterUsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdapterUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.AdapterUsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdapterUsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adapterprovider.AdapterUsageRecordsTable,
			Columns: []string{adapterprovider.AdapterUsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adapterusagerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdapterProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adapterprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
