// Code generated by ent, DO NOT EDIT.

package adapterrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldGroupID, v))
}

// AdapterProviderID applies equality check predicate on the "adapter_provider_id" field. It's identical to AdapterProviderIDEQ.
func AdapterProviderID(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldAdapterProviderID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldProvider, v))
}

// Capability applies equality check predicate on the "capability" field. It's identical to CapabilityEQ.
func Capability(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldCapability, v))
}

// RouteTarget applies equality check predicate on the "route_target" field. It's identical to RouteTargetEQ.
func RouteTarget(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldRouteTarget, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldPath, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldModel, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldGroupID))
}

// AdapterProviderIDEQ applies the EQ predicate on the "adapter_provider_id" field.
func AdapterProviderIDEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldAdapterProviderID, v))
}

// AdapterProviderIDNEQ applies the NEQ predicate on the "adapter_provider_id" field.
func AdapterProviderIDNEQ(v int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldAdapterProviderID, v))
}

// AdapterProviderIDIn applies the In predicate on the "adapter_provider_id" field.
func AdapterProviderIDIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldAdapterProviderID, vs...))
}

// AdapterProviderIDNotIn applies the NotIn predicate on the "adapter_provider_id" field.
func AdapterProviderIDNotIn(vs ...int64) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldAdapterProviderID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldProvider, v))
}

// CapabilityEQ applies the EQ predicate on the "capability" field.
func CapabilityEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldCapability, v))
}

// CapabilityNEQ applies the NEQ predicate on the "capability" field.
func CapabilityNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldCapability, v))
}

// CapabilityIn applies the In predicate on the "capability" field.
func CapabilityIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldCapability, vs...))
}

// CapabilityNotIn applies the NotIn predicate on the "capability" field.
func CapabilityNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldCapability, vs...))
}

// CapabilityGT applies the GT predicate on the "capability" field.
func CapabilityGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldCapability, v))
}

// CapabilityGTE applies the GTE predicate on the "capability" field.
func CapabilityGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldCapability, v))
}

// CapabilityLT applies the LT predicate on the "capability" field.
func CapabilityLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldCapability, v))
}

// CapabilityLTE applies the LTE predicate on the "capability" field.
func CapabilityLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldCapability, v))
}

// CapabilityContains applies the Contains predicate on the "capability" field.
func CapabilityContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldCapability, v))
}

// CapabilityHasPrefix applies the HasPrefix predicate on the "capability" field.
func CapabilityHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldCapability, v))
}

// CapabilityHasSuffix applies the HasSuffix predicate on the "capability" field.
func CapabilityHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldCapability, v))
}

// CapabilityEqualFold applies the EqualFold predicate on the "capability" field.
func CapabilityEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldCapability, v))
}

// CapabilityContainsFold applies the ContainsFold predicate on the "capability" field.
func CapabilityContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldCapability, v))
}

// RouteTargetEQ applies the EQ predicate on the "route_target" field.
func RouteTargetEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldRouteTarget, v))
}

// RouteTargetNEQ applies the NEQ predicate on the "route_target" field.
func RouteTargetNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldRouteTarget, v))
}

// RouteTargetIn applies the In predicate on the "route_target" field.
func RouteTargetIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldRouteTarget, vs...))
}

// RouteTargetNotIn applies the NotIn predicate on the "route_target" field.
func RouteTargetNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldRouteTarget, vs...))
}

// RouteTargetGT applies the GT predicate on the "route_target" field.
func RouteTargetGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldRouteTarget, v))
}

// RouteTargetGTE applies the GTE predicate on the "route_target" field.
func RouteTargetGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldRouteTarget, v))
}

// RouteTargetLT applies the LT predicate on the "route_target" field.
func RouteTargetLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldRouteTarget, v))
}

// RouteTargetLTE applies the LTE predicate on the "route_target" field.
func RouteTargetLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldRouteTarget, v))
}

// RouteTargetContains applies the Contains predicate on the "route_target" field.
func RouteTargetContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldRouteTarget, v))
}

// RouteTargetHasPrefix applies the HasPrefix predicate on the "route_target" field.
func RouteTargetHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldRouteTarget, v))
}

// RouteTargetHasSuffix applies the HasSuffix predicate on the "route_target" field.
func RouteTargetHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldRouteTarget, v))
}

// RouteTargetEqualFold applies the EqualFold predicate on the "route_target" field.
func RouteTargetEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldRouteTarget, v))
}

// RouteTargetContainsFold applies the ContainsFold predicate on the "route_target" field.
func RouteTargetContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldRouteTarget, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldPath, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldModel, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldStatusCode))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldContainsFold(FieldErrorMessage, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdapterProvider applies the HasEdge predicate on the "adapter_provider" edge.
func HasAdapterProvider() predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdapterProviderTable, AdapterProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdapterProviderWith applies the HasEdge predicate on the "adapter_provider" edge with a given conditions (other predicates).
func HasAdapterProviderWith(preds ...predicate.AdapterProvider) predicate.AdapterRequest {
	return predicate.AdapterRequest(func(s *sql.Selector) {
		step := newAdapterProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdapterRequest) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdapterRequest) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdapterRequest) predicate.AdapterRequest {
	return predicate.AdapterRequest(sql.NotPredicates(p))
}
