// Code generated by ent, DO NOT EDIT.

package adapterprovider

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adapterprovider type in the database.
	Label = "adapter_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAdapterType holds the string denoting the adapter_type field in the database.
	FieldAdapterType = "adapter_type"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldAuthMode holds the string denoting the auth_mode field in the database.
	FieldAuthMode = "auth_mode"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldTimeoutMs holds the string denoting the timeout_ms field in the database.
	FieldTimeoutMs = "timeout_ms"
	// FieldExtra holds the string denoting the extra field in the database.
	FieldExtra = "extra"
	// EdgeRoutePolicies holds the string denoting the route_policies edge name in mutations.
	EdgeRoutePolicies = "route_policies"
	// EdgeAdapterRequests holds the string denoting the adapter_requests edge name in mutations.
	EdgeAdapterRequests = "adapter_requests"
	// EdgeAdapterUsageRecords holds the string denoting the adapter_usage_records edge name in mutations.
	EdgeAdapterUsageRecords = "adapter_usage_records"
	// Table holds the table name of the adapterprovider in the database.
	Table = "adapter_providers"
	// RoutePoliciesTable is the table that holds the route_policies relation/edge.
	RoutePoliciesTable = "route_policies"
	// RoutePoliciesInverseTable is the table name for the RoutePolicy entity.
	// It exists in this package in order to avoid circular dependency with the "routepolicy" package.
	RoutePoliciesInverseTable = "route_policies"
	// RoutePoliciesColumn is the table column denoting the route_policies relation/edge.
	RoutePoliciesColumn = "adapter_provider_id"
	// AdapterRequestsTable is the table that holds the adapter_requests relation/edge.
	AdapterRequestsTable = "adapter_requests"
	// AdapterRequestsInverseTable is the table name for the AdapterRequest entity.
	// It exists in this package in order to avoid circular dependency with the "adapterrequest" package.
	AdapterRequestsInverseTable = "adapter_requests"
	// AdapterRequestsColumn is the table column denoting the adapter_requests relation/edge.
	AdapterRequestsColumn = "adapter_provider_id"
	// AdapterUsageRecordsTable is the table that holds the adapter_usage_records relation/edge.
	AdapterUsageRecordsTable = "adapter_usage_records"
	// AdapterUsageRecordsInverseTable is the table name for the AdapterUsageRecord entity.
	// It exists in this package in order to avoid circular dependency with the "adapterusagerecord" package.
	AdapterUsageRecordsInverseTable = "adapter_usage_records"
	// AdapterUsageRecordsColumn is the table column denoting the adapter_usage_records relation/edge.
	AdapterUsageRecordsColumn = "adapter_provider_id"
)

// Columns holds all SQL columns for adapterprovider fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSlug,
	FieldStatus,
	FieldAdapterType,
	FieldBaseURL,
	FieldAuthMode,
	FieldCredentials,
	FieldCapabilities,
	FieldPriority,
	FieldTimeoutMs,
	FieldExtra,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultAdapterType holds the default value on creation for the "adapter_type" field.
	DefaultAdapterType string
	// AdapterTypeValidator is a validator for the "adapter_type" field. It is called by the builders before save.
	AdapterTypeValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// AuthModeValidator is a validator for the "auth_mode" field. It is called by the builders before save.
	AuthModeValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultTimeoutMs holds the default value on creation for the "timeout_ms" field.
	DefaultTimeoutMs int
)

// OrderOption defines the ordering options for the AdapterProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAdapterType orders the results by the adapter_type field.
func ByAdapterType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapterType, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByAuthMode orders the results by the auth_mode field.
func ByAuthMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMode, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByTimeoutMs orders the results by the timeout_ms field.
func ByTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMs, opts...).ToFunc()
}

// ByRoutePoliciesCount orders the results by route_policies count.
func ByRoutePoliciesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoutePoliciesStep(), opts...)
	}
}

// ByRoutePolicies orders the results by route_policies terms.
func ByRoutePolicies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoutePoliciesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAdapterRequestsCount orders the results by adapter_requests count.
func ByAdapterRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdapterRequestsStep(), opts...)
	}
}

// ByAdapterRequests orders the results by adapter_requests terms.
func ByAdapterRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdapterRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAdapterUsageRecordsCount orders the results by adapter_usage_records count.
func ByAdapterUsageRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdapterUsageRecordsStep(), opts...)
	}
}

// ByAdapterUsageRecords orders the results by adapter_usage_records terms.
func ByAdapterUsageRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdapterUsageRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRoutePoliciesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoutePoliciesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoutePoliciesTable, RoutePoliciesColumn),
	)
}
func newAdapterRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdapterRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdapterRequestsTable, AdapterRequestsColumn),
	)
}
func newAdapterUsageRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdapterUsageRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdapterUsageRecordsTable, AdapterUsageRecordsColumn),
	)
}
