// Code generated by ent, DO NOT EDIT.

package adapterprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldSlug, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldStatus, v))
}

// AdapterType applies equality check predicate on the "adapter_type" field. It's identical to AdapterTypeEQ.
func AdapterType(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldAdapterType, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldBaseURL, v))
}

// AuthMode applies equality check predicate on the "auth_mode" field. It's identical to AuthModeEQ.
func AuthMode(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldAuthMode, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldPriority, v))
}

// TimeoutMs applies equality check predicate on the "timeout_ms" field. It's identical to TimeoutMsEQ.
func TimeoutMs(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldTimeoutMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldSlug, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldStatus, v))
}

// AdapterTypeEQ applies the EQ predicate on the "adapter_type" field.
func AdapterTypeEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldAdapterType, v))
}

// AdapterTypeNEQ applies the NEQ predicate on the "adapter_type" field.
func AdapterTypeNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldAdapterType, v))
}

// AdapterTypeIn applies the In predicate on the "adapter_type" field.
func AdapterTypeIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldAdapterType, vs...))
}

// AdapterTypeNotIn applies the NotIn predicate on the "adapter_type" field.
func AdapterTypeNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldAdapterType, vs...))
}

// AdapterTypeGT applies the GT predicate on the "adapter_type" field.
func AdapterTypeGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldAdapterType, v))
}

// AdapterTypeGTE applies the GTE predicate on the "adapter_type" field.
func AdapterTypeGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldAdapterType, v))
}

// AdapterTypeLT applies the LT predicate on the "adapter_type" field.
func AdapterTypeLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldAdapterType, v))
}

// AdapterTypeLTE applies the LTE predicate on the "adapter_type" field.
func AdapterTypeLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldAdapterType, v))
}

// AdapterTypeContains applies the Contains predicate on the "adapter_type" field.
func AdapterTypeContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldAdapterType, v))
}

// AdapterTypeHasPrefix applies the HasPrefix predicate on the "adapter_type" field.
func AdapterTypeHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldAdapterType, v))
}

// AdapterTypeHasSuffix applies the HasSuffix predicate on the "adapter_type" field.
func AdapterTypeHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldAdapterType, v))
}

// AdapterTypeEqualFold applies the EqualFold predicate on the "adapter_type" field.
func AdapterTypeEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldAdapterType, v))
}

// AdapterTypeContainsFold applies the ContainsFold predicate on the "adapter_type" field.
func AdapterTypeContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldAdapterType, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldBaseURL, v))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldAuthMode, vs...))
}

// AuthModeGT applies the GT predicate on the "auth_mode" field.
func AuthModeGT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldAuthMode, v))
}

// AuthModeGTE applies the GTE predicate on the "auth_mode" field.
func AuthModeGTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldAuthMode, v))
}

// AuthModeLT applies the LT predicate on the "auth_mode" field.
func AuthModeLT(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldAuthMode, v))
}

// AuthModeLTE applies the LTE predicate on the "auth_mode" field.
func AuthModeLTE(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldAuthMode, v))
}

// AuthModeContains applies the Contains predicate on the "auth_mode" field.
func AuthModeContains(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContains(FieldAuthMode, v))
}

// AuthModeHasPrefix applies the HasPrefix predicate on the "auth_mode" field.
func AuthModeHasPrefix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasPrefix(FieldAuthMode, v))
}

// AuthModeHasSuffix applies the HasSuffix predicate on the "auth_mode" field.
func AuthModeHasSuffix(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldHasSuffix(FieldAuthMode, v))
}

// AuthModeIsNil applies the IsNil predicate on the "auth_mode" field.
func AuthModeIsNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIsNull(FieldAuthMode))
}

// AuthModeNotNil applies the NotNil predicate on the "auth_mode" field.
func AuthModeNotNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotNull(FieldAuthMode))
}

// AuthModeEqualFold applies the EqualFold predicate on the "auth_mode" field.
func AuthModeEqualFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEqualFold(FieldAuthMode, v))
}

// AuthModeContainsFold applies the ContainsFold predicate on the "auth_mode" field.
func AuthModeContainsFold(v string) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldContainsFold(FieldAuthMode, v))
}

// CredentialsIsNil applies the IsNil predicate on the "credentials" field.
func CredentialsIsNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIsNull(FieldCredentials))
}

// CredentialsNotNil applies the NotNil predicate on the "credentials" field.
func CredentialsNotNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotNull(FieldCredentials))
}

// CapabilitiesIsNil applies the IsNil predicate on the "capabilities" field.
func CapabilitiesIsNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIsNull(FieldCapabilities))
}

// CapabilitiesNotNil applies the NotNil predicate on the "capabilities" field.
func CapabilitiesNotNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotNull(FieldCapabilities))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldPriority, v))
}

// TimeoutMsEQ applies the EQ predicate on the "timeout_ms" field.
func TimeoutMsEQ(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldEQ(FieldTimeoutMs, v))
}

// TimeoutMsNEQ applies the NEQ predicate on the "timeout_ms" field.
func TimeoutMsNEQ(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNEQ(FieldTimeoutMs, v))
}

// TimeoutMsIn applies the In predicate on the "timeout_ms" field.
func TimeoutMsIn(vs ...int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIn(FieldTimeoutMs, vs...))
}

// TimeoutMsNotIn applies the NotIn predicate on the "timeout_ms" field.
func TimeoutMsNotIn(vs ...int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotIn(FieldTimeoutMs, vs...))
}

// TimeoutMsGT applies the GT predicate on the "timeout_ms" field.
func TimeoutMsGT(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGT(FieldTimeoutMs, v))
}

// TimeoutMsGTE applies the GTE predicate on the "timeout_ms" field.
func TimeoutMsGTE(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldGTE(FieldTimeoutMs, v))
}

// TimeoutMsLT applies the LT predicate on the "timeout_ms" field.
func TimeoutMsLT(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLT(FieldTimeoutMs, v))
}

// TimeoutMsLTE applies the LTE predicate on the "timeout_ms" field.
func TimeoutMsLTE(v int) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldLTE(FieldTimeoutMs, v))
}

// ExtraIsNil applies the IsNil predicate on the "extra" field.
func ExtraIsNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldIsNull(FieldExtra))
}

// ExtraNotNil applies the NotNil predicate on the "extra" field.
func ExtraNotNil() predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.FieldNotNull(FieldExtra))
}

// HasRoutePolicies applies the HasEdge predicate on the "route_policies" edge.
func HasRoutePolicies() predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RoutePoliciesTable, RoutePoliciesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoutePoliciesWith applies the HasEdge predicate on the "route_policies" edge with a given conditions (other predicates).
func HasRoutePoliciesWith(preds ...predicate.RoutePolicy) predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := newRoutePoliciesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdapterRequests applies the HasEdge predicate on the "adapter_requests" edge.
func HasAdapterRequests() predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdapterRequestsTable, AdapterRequestsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdapterRequestsWith applies the HasEdge predicate on the "adapter_requests" edge with a given conditions (other predicates).
func HasAdapterRequestsWith(preds ...predicate.AdapterRequest) predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := newAdapterRequestsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdapterUsageRecords applies the HasEdge predicate on the "adapter_usage_records" edge.
func HasAdapterUsageRecords() predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdapterUsageRecordsTable, AdapterUsageRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdapterUsageRecordsWith applies the HasEdge predicate on the "adapter_usage_records" edge with a given conditions (other predicates).
func HasAdapterUsageRecordsWith(preds ...predicate.AdapterUsageRecord) predicate.AdapterProvider {
	return predicate.AdapterProvider(func(s *sql.Selector) {
		step := newAdapterUsageRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdapterProvider) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdapterProvider) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdapterProvider) predicate.AdapterProvider {
	return predicate.AdapterProvider(sql.NotPredicates(p))
}
