// Code generated by ent, DO NOT EDIT.

package adapterusagerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldGroupID, v))
}

// AdapterProviderID applies equality check predicate on the "adapter_provider_id" field. It's identical to AdapterProviderIDEQ.
func AdapterProviderID(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldAdapterProviderID, v))
}

// RoutePolicyID applies equality check predicate on the "route_policy_id" field. It's identical to RoutePolicyIDEQ.
func RoutePolicyID(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldRoutePolicyID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldProvider, v))
}

// Capability applies equality check predicate on the "capability" field. It's identical to CapabilityEQ.
func Capability(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCapability, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldModel, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldPath, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldErrorMessage, v))
}

// InputUnits applies equality check predicate on the "input_units" field. It's identical to InputUnitsEQ.
func InputUnits(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldInputUnits, v))
}

// OutputUnits applies equality check predicate on the "output_units" field. It's identical to OutputUnitsEQ.
func OutputUnits(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldOutputUnits, v))
}

// BillableUnits applies equality check predicate on the "billable_units" field. It's identical to BillableUnitsEQ.
func BillableUnits(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillableUnits, v))
}

// CostUsd applies equality check predicate on the "cost_usd" field. It's identical to CostUsdEQ.
func CostUsd(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCostUsd, v))
}

// BillableUnit applies equality check predicate on the "billable_unit" field. It's identical to BillableUnitEQ.
func BillableUnit(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillableUnit, v))
}

// BillingApplied applies equality check predicate on the "billing_applied" field. It's identical to BillingAppliedEQ.
func BillingApplied(v bool) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillingApplied, v))
}

// BillingFingerprint applies equality check predicate on the "billing_fingerprint" field. It's identical to BillingFingerprintEQ.
func BillingFingerprint(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillingFingerprint, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldGroupID))
}

// AdapterProviderIDEQ applies the EQ predicate on the "adapter_provider_id" field.
func AdapterProviderIDEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldAdapterProviderID, v))
}

// AdapterProviderIDNEQ applies the NEQ predicate on the "adapter_provider_id" field.
func AdapterProviderIDNEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldAdapterProviderID, v))
}

// AdapterProviderIDIn applies the In predicate on the "adapter_provider_id" field.
func AdapterProviderIDIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldAdapterProviderID, vs...))
}

// AdapterProviderIDNotIn applies the NotIn predicate on the "adapter_provider_id" field.
func AdapterProviderIDNotIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldAdapterProviderID, vs...))
}

// RoutePolicyIDEQ applies the EQ predicate on the "route_policy_id" field.
func RoutePolicyIDEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldRoutePolicyID, v))
}

// RoutePolicyIDNEQ applies the NEQ predicate on the "route_policy_id" field.
func RoutePolicyIDNEQ(v int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldRoutePolicyID, v))
}

// RoutePolicyIDIn applies the In predicate on the "route_policy_id" field.
func RoutePolicyIDIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldRoutePolicyID, vs...))
}

// RoutePolicyIDNotIn applies the NotIn predicate on the "route_policy_id" field.
func RoutePolicyIDNotIn(vs ...int64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldRoutePolicyID, vs...))
}

// RoutePolicyIDIsNil applies the IsNil predicate on the "route_policy_id" field.
func RoutePolicyIDIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldRoutePolicyID))
}

// RoutePolicyIDNotNil applies the NotNil predicate on the "route_policy_id" field.
func RoutePolicyIDNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldRoutePolicyID))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldProvider, v))
}

// CapabilityEQ applies the EQ predicate on the "capability" field.
func CapabilityEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCapability, v))
}

// CapabilityNEQ applies the NEQ predicate on the "capability" field.
func CapabilityNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldCapability, v))
}

// CapabilityIn applies the In predicate on the "capability" field.
func CapabilityIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldCapability, vs...))
}

// CapabilityNotIn applies the NotIn predicate on the "capability" field.
func CapabilityNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldCapability, vs...))
}

// CapabilityGT applies the GT predicate on the "capability" field.
func CapabilityGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldCapability, v))
}

// CapabilityGTE applies the GTE predicate on the "capability" field.
func CapabilityGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldCapability, v))
}

// CapabilityLT applies the LT predicate on the "capability" field.
func CapabilityLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldCapability, v))
}

// CapabilityLTE applies the LTE predicate on the "capability" field.
func CapabilityLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldCapability, v))
}

// CapabilityContains applies the Contains predicate on the "capability" field.
func CapabilityContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldCapability, v))
}

// CapabilityHasPrefix applies the HasPrefix predicate on the "capability" field.
func CapabilityHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldCapability, v))
}

// CapabilityHasSuffix applies the HasSuffix predicate on the "capability" field.
func CapabilityHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldCapability, v))
}

// CapabilityEqualFold applies the EqualFold predicate on the "capability" field.
func CapabilityEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldCapability, v))
}

// CapabilityContainsFold applies the ContainsFold predicate on the "capability" field.
func CapabilityContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldCapability, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldModel, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodIsNil applies the IsNil predicate on the "method" field.
func MethodIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldMethod))
}

// MethodNotNil applies the NotNil predicate on the "method" field.
func MethodNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldMethod))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldPath, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldStatus, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldStatusCode))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldErrorMessage, v))
}

// InputUnitsEQ applies the EQ predicate on the "input_units" field.
func InputUnitsEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldInputUnits, v))
}

// InputUnitsNEQ applies the NEQ predicate on the "input_units" field.
func InputUnitsNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldInputUnits, v))
}

// InputUnitsIn applies the In predicate on the "input_units" field.
func InputUnitsIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldInputUnits, vs...))
}

// InputUnitsNotIn applies the NotIn predicate on the "input_units" field.
func InputUnitsNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldInputUnits, vs...))
}

// InputUnitsGT applies the GT predicate on the "input_units" field.
func InputUnitsGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldInputUnits, v))
}

// InputUnitsGTE applies the GTE predicate on the "input_units" field.
func InputUnitsGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldInputUnits, v))
}

// InputUnitsLT applies the LT predicate on the "input_units" field.
func InputUnitsLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldInputUnits, v))
}

// InputUnitsLTE applies the LTE predicate on the "input_units" field.
func InputUnitsLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldInputUnits, v))
}

// OutputUnitsEQ applies the EQ predicate on the "output_units" field.
func OutputUnitsEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldOutputUnits, v))
}

// OutputUnitsNEQ applies the NEQ predicate on the "output_units" field.
func OutputUnitsNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldOutputUnits, v))
}

// OutputUnitsIn applies the In predicate on the "output_units" field.
func OutputUnitsIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldOutputUnits, vs...))
}

// OutputUnitsNotIn applies the NotIn predicate on the "output_units" field.
func OutputUnitsNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldOutputUnits, vs...))
}

// OutputUnitsGT applies the GT predicate on the "output_units" field.
func OutputUnitsGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldOutputUnits, v))
}

// OutputUnitsGTE applies the GTE predicate on the "output_units" field.
func OutputUnitsGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldOutputUnits, v))
}

// OutputUnitsLT applies the LT predicate on the "output_units" field.
func OutputUnitsLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldOutputUnits, v))
}

// OutputUnitsLTE applies the LTE predicate on the "output_units" field.
func OutputUnitsLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldOutputUnits, v))
}

// BillableUnitsEQ applies the EQ predicate on the "billable_units" field.
func BillableUnitsEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillableUnits, v))
}

// BillableUnitsNEQ applies the NEQ predicate on the "billable_units" field.
func BillableUnitsNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldBillableUnits, v))
}

// BillableUnitsIn applies the In predicate on the "billable_units" field.
func BillableUnitsIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldBillableUnits, vs...))
}

// BillableUnitsNotIn applies the NotIn predicate on the "billable_units" field.
func BillableUnitsNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldBillableUnits, vs...))
}

// BillableUnitsGT applies the GT predicate on the "billable_units" field.
func BillableUnitsGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldBillableUnits, v))
}

// BillableUnitsGTE applies the GTE predicate on the "billable_units" field.
func BillableUnitsGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldBillableUnits, v))
}

// BillableUnitsLT applies the LT predicate on the "billable_units" field.
func BillableUnitsLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldBillableUnits, v))
}

// BillableUnitsLTE applies the LTE predicate on the "billable_units" field.
func BillableUnitsLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldBillableUnits, v))
}

// CostUsdEQ applies the EQ predicate on the "cost_usd" field.
func CostUsdEQ(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCostUsd, v))
}

// CostUsdNEQ applies the NEQ predicate on the "cost_usd" field.
func CostUsdNEQ(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldCostUsd, v))
}

// CostUsdIn applies the In predicate on the "cost_usd" field.
func CostUsdIn(vs ...float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldCostUsd, vs...))
}

// CostUsdNotIn applies the NotIn predicate on the "cost_usd" field.
func CostUsdNotIn(vs ...float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldCostUsd, vs...))
}

// CostUsdGT applies the GT predicate on the "cost_usd" field.
func CostUsdGT(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldCostUsd, v))
}

// CostUsdGTE applies the GTE predicate on the "cost_usd" field.
func CostUsdGTE(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldCostUsd, v))
}

// CostUsdLT applies the LT predicate on the "cost_usd" field.
func CostUsdLT(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldCostUsd, v))
}

// CostUsdLTE applies the LTE predicate on the "cost_usd" field.
func CostUsdLTE(v float64) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldCostUsd, v))
}

// BillableUnitEQ applies the EQ predicate on the "billable_unit" field.
func BillableUnitEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillableUnit, v))
}

// BillableUnitNEQ applies the NEQ predicate on the "billable_unit" field.
func BillableUnitNEQ(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldBillableUnit, v))
}

// BillableUnitIn applies the In predicate on the "billable_unit" field.
func BillableUnitIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldBillableUnit, vs...))
}

// BillableUnitNotIn applies the NotIn predicate on the "billable_unit" field.
func BillableUnitNotIn(vs ...int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldBillableUnit, vs...))
}

// BillableUnitGT applies the GT predicate on the "billable_unit" field.
func BillableUnitGT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldBillableUnit, v))
}

// BillableUnitGTE applies the GTE predicate on the "billable_unit" field.
func BillableUnitGTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldBillableUnit, v))
}

// BillableUnitLT applies the LT predicate on the "billable_unit" field.
func BillableUnitLT(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldBillableUnit, v))
}

// BillableUnitLTE applies the LTE predicate on the "billable_unit" field.
func BillableUnitLTE(v int) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldBillableUnit, v))
}

// BillingAppliedEQ applies the EQ predicate on the "billing_applied" field.
func BillingAppliedEQ(v bool) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillingApplied, v))
}

// BillingAppliedNEQ applies the NEQ predicate on the "billing_applied" field.
func BillingAppliedNEQ(v bool) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldBillingApplied, v))
}

// BillingFingerprintEQ applies the EQ predicate on the "billing_fingerprint" field.
func BillingFingerprintEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldBillingFingerprint, v))
}

// BillingFingerprintNEQ applies the NEQ predicate on the "billing_fingerprint" field.
func BillingFingerprintNEQ(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldBillingFingerprint, v))
}

// BillingFingerprintIn applies the In predicate on the "billing_fingerprint" field.
func BillingFingerprintIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldBillingFingerprint, vs...))
}

// BillingFingerprintNotIn applies the NotIn predicate on the "billing_fingerprint" field.
func BillingFingerprintNotIn(vs ...string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldBillingFingerprint, vs...))
}

// BillingFingerprintGT applies the GT predicate on the "billing_fingerprint" field.
func BillingFingerprintGT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldBillingFingerprint, v))
}

// BillingFingerprintGTE applies the GTE predicate on the "billing_fingerprint" field.
func BillingFingerprintGTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldBillingFingerprint, v))
}

// BillingFingerprintLT applies the LT predicate on the "billing_fingerprint" field.
func BillingFingerprintLT(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldBillingFingerprint, v))
}

// BillingFingerprintLTE applies the LTE predicate on the "billing_fingerprint" field.
func BillingFingerprintLTE(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldBillingFingerprint, v))
}

// BillingFingerprintContains applies the Contains predicate on the "billing_fingerprint" field.
func BillingFingerprintContains(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContains(FieldBillingFingerprint, v))
}

// BillingFingerprintHasPrefix applies the HasPrefix predicate on the "billing_fingerprint" field.
func BillingFingerprintHasPrefix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasPrefix(FieldBillingFingerprint, v))
}

// BillingFingerprintHasSuffix applies the HasSuffix predicate on the "billing_fingerprint" field.
func BillingFingerprintHasSuffix(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldHasSuffix(FieldBillingFingerprint, v))
}

// BillingFingerprintIsNil applies the IsNil predicate on the "billing_fingerprint" field.
func BillingFingerprintIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldBillingFingerprint))
}

// BillingFingerprintNotNil applies the NotNil predicate on the "billing_fingerprint" field.
func BillingFingerprintNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldBillingFingerprint))
}

// BillingFingerprintEqualFold applies the EqualFold predicate on the "billing_fingerprint" field.
func BillingFingerprintEqualFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEqualFold(FieldBillingFingerprint, v))
}

// BillingFingerprintContainsFold applies the ContainsFold predicate on the "billing_fingerprint" field.
func BillingFingerprintContainsFold(v string) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldContainsFold(FieldBillingFingerprint, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdapterProvider applies the HasEdge predicate on the "adapter_provider" edge.
func HasAdapterProvider() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdapterProviderTable, AdapterProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdapterProviderWith applies the HasEdge predicate on the "adapter_provider" edge with a given conditions (other predicates).
func HasAdapterProviderWith(preds ...predicate.AdapterProvider) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := newAdapterProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoutePolicy applies the HasEdge predicate on the "route_policy" edge.
func HasRoutePolicy() predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoutePolicyTable, RoutePolicyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoutePolicyWith applies the HasEdge predicate on the "route_policy" edge with a given conditions (other predicates).
func HasRoutePolicyWith(preds ...predicate.RoutePolicy) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(func(s *sql.Selector) {
		step := newRoutePolicyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdapterUsageRecord) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdapterUsageRecord) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdapterUsageRecord) predicate.AdapterUsageRecord {
	return predicate.AdapterUsageRecord(sql.NotPredicates(p))
}
